<?php
/**
 * Tematres Suggest
 *
 * @copyright Copyright 2025 Diego Ferreyra
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GNU GPLv3
 */

/**
 * Tematres Suggest plugin.
 *
**/
/**
 * The T3_suggests table.
 *
 * @package Omeka\Plugins\T3Suggest
 */
class Table_T3Suggest extends Omeka_Db_Table
{
    /**
     * List of some suggest endpoints available in Tematres. You can add your own vocabulary or see the the know case list of Tematres vocabularies in https://vocabularyserver.com/vocabularies/
     *
     *
     * @see https://vocabularyserver.com/vocabularies/
     */
    private $_suggestEndpoints = array(
'https://vocabularyserver.com/glin/ar/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'Arabic', 'url'=> 'https://vocabularyserver.com/glin/ar/'),
'https://vocabularyserver.com/ddc/ar/suggest.php' => array('name' =>  'تصنيف ديوي العشري','lang'=>'Arabic', 'url'=> 'https://vocabularyserver.com/ddc/ar/'),
'https://vocabularyserver.com/unbis/ar/suggest.php' => array('name' =>  'مكنز الببليوغرافية (UNBIS)','lang'=>'Arabic', 'url'=> 'https://vocabularyserver.com/unbis/ar/'),
'https://vocabularyserver.com/tee/eu/suggest.php' => array('name' =>  'Hezkuntzako europar tesauroaren','lang'=>'Basque', 'url'=> 'https://vocabularyserver.com/tee/eu/'),
'https://vocabularyserver.com/eurovoc/bg/suggest.php' => array('name' =>  'Eurovoc, многоезичен речник на Европейския съюз','lang'=>'Bulgarian', 'url'=> 'https://vocabularyserver.com/eurovoc/bg/'),
'https://vocabularyserver.com/historia_catalunya/suggest.php' => array('name' =>  'Tesaurus d\'Història de Catalunya','lang'=>'Catalan', 'url'=> 'https://vocabularyserver.com/historia_catalunya/'),
'https://vocabularyserver.com/traces/ca/suggest.php' => array('name' =>  'Tesaurus de Llengua i Literatura','lang'=>'Catalan', 'url'=> 'https://vocabularyserver.com/traces/ca/'),
'https://vocabularyserver.com/tee/ca/suggest.php' => array('name' =>  'Tesaurus Europeu de l\'Educació','lang'=>'Catalan', 'url'=> 'https://vocabularyserver.com/tee/ca/'),
'https://vocabularyserver.com/gemet/cn/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Chinese', 'url'=> 'https://vocabularyserver.com/gemet/cn/'),
'https://vocabularyserver.com/sop/suggest.php' => array('name' =>  'Sustavi za označivanje i pretraživanje','lang'=>'Croatian', 'url'=> 'https://vocabularyserver.com/sop/'),
'https://vocabularyserver.com/eurovoc/cs/suggest.php' => array('name' =>  'Eurovoc, mnohojazy?ný tezaurus Evropské unie','lang'=>'Czech', 'url'=> 'https://vocabularyserver.com/eurovoc/cs/'),
'https://vocabularyserver.com/psh/cs/suggest.php' => array('name' =>  'Polytematický strukturovaný heslá?','lang'=>'Czech', 'url'=> 'https://vocabularyserver.com/psh/cs/'),
'https://vocabularyserver.com/eurovoc/nl/suggest.php' => array('name' =>  'Eurovoc, meertalige thesaurus van de Europese Unie','lang'=>'Dutch', 'url'=> 'https://vocabularyserver.com/eurovoc/nl/'),
'https://vocabularyserver.com/lre/nl/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Dutch', 'url'=> 'https://vocabularyserver.com/lre/nl/'),
'https://vocabularyserver.com/atu/en/suggest.php' => array('name' =>  'Aarne-Thompson-Uther Classification of Folk Tales','lang'=>'English', 'url'=> 'https://vocabularyserver.com/atu/en/'),
'https://vocabularyserver.com/glossaries/cdd/suggest.php' => array('name' =>  'Dewey Decimal Classification glossary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/cdd/'),
'https://vocabularyserver.com/det/en/services.phpsuggest.php' => array('name' =>  'Digital Europa Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/det/en/services.php'),
'https://vocabularyserver.com/ford/es/services.phpsuggest.php' => array('name' =>  'Fields of Research and Development classification (FORD)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ford/es/services.php'),
'https://vocabularyserver.com/fastgenre/en/suggest.php' => array('name' =>  'Form and Genre Headings','lang'=>'English', 'url'=> 'https://vocabularyserver.com/fastgenre/en/'),
'https://vocabularyserver.com/fiaf/suggest.php' => array('name' =>  'General subject headings for Film Archives','lang'=>'English', 'url'=> 'https://vocabularyserver.com/fiaf/'),
'https://vocabularyserver.com/linguisticterms/suggest.php' => array('name' =>  'Glossary of Linguistic Terms','lang'=>'English', 'url'=> 'https://vocabularyserver.com/linguisticterms/'),
'https://vocabularyserver.com/glossaries/z3919/suggest.php' => array('name' =>  'Guidelines for the Construction, Format, and Management of Monolingual Controlled Vocabularies','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/z3919/'),
'https://vocabularyserver.com/ieee/thesaurus/services.phpsuggest.php' => array('name' =>  'IEEE Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ieee/thesaurus/services.php'),
'https://vocabularyserver.com/jel/en/services.phpsuggest.php' => array('name' =>  'JEL Classification System / EconLit Subject Descriptors','lang'=>'English', 'url'=> 'https://vocabularyserver.com/jel/en/services.php'),
'https://vocabularyserver.com/wals/en/services.phpsuggest.php' => array('name' =>  'Language features to cross-linguistic description (WALS)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/wals/en/services.php'),
'https://vocabularyserver.com/motif/en/suggest.php' => array('name' =>  'Motif-Index of Folk-Literature','lang'=>'English', 'url'=> 'https://vocabularyserver.com/motif/en/'),
'https://vocabularyserver.com/muldicat/en/services.phpsuggest.php' => array('name' =>  'Multilingual dictionary of cataloguing terms and concepts (MulDiCat)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/muldicat/en/services.php'),
'https://vocabularyserver.com/opensciencethes/en/services.phpsuggest.php' => array('name' =>  'Open science thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/opensciencethes/en/services.php'),
'https://vocabularyserver.com/pipfilm/suggest.php' => array('name' =>  'P.I.P. Subject Headings','lang'=>'English', 'url'=> 'https://vocabularyserver.com/pipfilm/'),
'https://vocabularyserver.com/physh/suggest.php' => array('name' =>  'Physics Subject Headings - Physh','lang'=>'English', 'url'=> 'https://vocabularyserver.com/physh/'),
'https://vocabularyserver.com/psh/en/suggest.php' => array('name' =>  'Polythematic Structured Subject Heading System','lang'=>'English', 'url'=> 'https://vocabularyserver.com/psh/en/'),
'https://vocabularyserver.com/acl/suggest.php' => array('name' =>  'ACLearn','lang'=>'English', 'url'=> 'https://vocabularyserver.com/acl/'),
'https://vocabularyserver.com/agcom/suggest.php' => array('name' =>  'Agricultural Communications Thesaurus (AGCOM)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/agcom/'),
'https://vocabularyserver.com/agrovoc/en/suggest.php' => array('name' =>  'AGROVOC Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/agrovoc/en/'),
'https://vocabularyserver.com/adl/suggest.php' => array('name' =>  'Alexandria Digital Library Feature Type Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/adl/'),
'https://vocabularyserver.com/anaeethes/suggest.php' => array('name' =>  'AnaEE Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/anaeethes/'),
'https://vocabularyserver.com/animals/suggest.php' => array('name' =>  'Animal Use Alternatives Thesaurus Terminology','lang'=>'English', 'url'=> 'https://vocabularyserver.com/animals/'),
'https://vocabularyserver.com/apais/suggest.php' => array('name' =>  'APAIS Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/apais/'),
'https://vocabularyserver.com/apt/suggest.php' => array('name' =>  'APT Australian Pictorial Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/apt/'),
'https://vocabularyserver.com/asfa/suggest.php' => array('name' =>  'Aquatic Sciences and Fisheries Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/asfa/'),
'https://vocabularyserver.com/anzsrc/suggest.php' => array('name' =>  'Australian and New Zealand Standard Research Classification','lang'=>'English', 'url'=> 'https://vocabularyserver.com/anzsrc/'),
'https://vocabularyserver.com/agift/suggest.php' => array('name' =>  'Australian Governments\' Interactive Functions Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/agift/'),
'https://vocabularyserver.com/bll/en/suggest.php' => array('name' =>  'Bibliography of Linguistic Literature Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/bll/en/'),
'https://vocabularyserver.com/materials/suggest.php' => array('name' =>  'British Museum Materials Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/materials/'),
'https://vocabularyserver.com/objects/suggest.php' => array('name' =>  'British Museum Object Names Theasarus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/objects/'),
'https://vocabularyserver.com/csps/suggest.php' => array('name' =>  'Canada School of Public Service Controlled Vocabulary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/csps/'),
'https://vocabularyserver.com/cofog/en/suggest.php' => array('name' =>  'Classification of the Functions of Government','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cofog/en/'),
'https://vocabularyserver.com/ko/suggest.php' => array('name' =>  'Classification System for Knowledge Organization Literature','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ko/'),
'https://vocabularyserver.com/cso/suggest.php' => array('name' =>  'Computer Science Ontology (CSO)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cso/'),
'https://vocabularyserver.com/glossaries/boxesarrows/suggest.php' => array('name' =>  'Controlled Vocabularies: A Glosso-Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/boxesarrows/'),
'https://vocabularyserver.com/cbdvoc/suggest.php' => array('name' =>  'Convention of Biological Diversity Controlled Vocabulary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cbdvoc/'),
'https://vocabularyserver.com/thomas/suggest.php' => array('name' =>  'CRS Legislative Subject Terms Used in THOMAS','lang'=>'English', 'url'=> 'https://vocabularyserver.com/thomas/'),
'https://vocabularyserver.com/ddc/en/suggest.php' => array('name' =>  'Dewey Decimal Classification (DDC)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ddc/en/'),
'https://vocabularyserver.com/dhthesaurus/suggest.php' => array('name' =>  'Digital Humanities Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/dhthesaurus/'),
'https://vocabularyserver.com/dtic/suggest.php' => array('name' =>  'DTIC Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/dtic/'),
'https://vocabularyserver.com/cnr/ml/earth/en/suggest.php' => array('name' =>  'EARTh - Environmental Applications Reference Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cnr/ml/earth/en/'),
'https://vocabularyserver.com/cnr/ml/eosterm/en/suggest.php' => array('name' =>  'EOSterm','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cnr/ml/eosterm/en/'),
'https://vocabularyserver.com/eric/suggest.php' => array('name' =>  'ERIC Thesurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/eric/'),
'https://vocabularyserver.com/etnography/suggest.php' => array('name' =>  'Ethnographic Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/etnography/'),
'https://vocabularyserver.com/tee/en/suggest.php' => array('name' =>  'European Education Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/tee/en/'),
'https://vocabularyserver.com/hpmulti/en/suggest.php' => array('name' =>  'European multilingual thesaurus on health promotion','lang'=>'English', 'url'=> 'https://vocabularyserver.com/hpmulti/en/'),
'https://vocabularyserver.com/ett/suggest.php' => array('name' =>  'European Training Thesaurus - ETT','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ett/'),
'https://vocabularyserver.com/eurovoc/en/suggest.php' => array('name' =>  'Eurovoc, the EU\'s multilingual  thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/eurovoc/en/'),
'https://vocabularyserver.com/taxoko/suggest.php' => array('name' =>  'Formal Taxonomy of Knowledge Organization','lang'=>'English', 'url'=> 'https://vocabularyserver.com/taxoko/'),
'https://vocabularyserver.com/fonz/suggest.php' => array('name' =>  'Functions of New Zealand Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/fonz/'),
'https://vocabularyserver.com/gemet/en/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/gemet/en/'),
'https://vocabularyserver.com/eige/suggest.php' => array('name' =>  'Gender Equality Glossary and Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/eige/'),
'https://vocabularyserver.com/lawgenre/suggest.php' => array('name' =>  'Genre/Form Terms for Law Materials','lang'=>'English', 'url'=> 'https://vocabularyserver.com/lawgenre/'),
'https://vocabularyserver.com/cnr/ml/geotermthes/en/suggest.php' => array('name' =>  'Geothermal Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cnr/ml/geotermthes/en/'),
'https://vocabularyserver.com/glin/en/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glin/en/'),
'https://vocabularyserver.com/glossaries/getty/suggest.php' => array('name' =>  'Glossary about Controlled Vocabularies','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/getty/'),
'https://vocabularyserver.com/nalglossary/en/suggest.php' => array('name' =>  'Glossary of Agricultural Terms','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nalglossary/en/'),
'https://vocabularyserver.com/glossaries/willpower/suggest.php' => array('name' =>  'Glossary of terms relating to thesauri and other forms of        structured vocabulary for information retrieval','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/willpower/'),
'https://vocabularyserver.com/cst/suggest.php' => array('name' =>  'Government of Canada Core Subject Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cst/'),
'https://vocabularyserver.com/concepts/en/suggest.php' => array('name' =>  'Guidelines for concept analysis: glossary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/concepts/en/'),
'https://vocabularyserver.com/harrypotter/suggest.php' => array('name' =>  'Harry Potter Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/harrypotter/'),
'https://vocabularyserver.com/homosaurus/suggest.php' => array('name' =>  'Homosaurus Vocabulary Terms','lang'=>'English', 'url'=> 'https://vocabularyserver.com/homosaurus/'),
'https://vocabularyserver.com/hasset/suggest.php' => array('name' =>  'Humanities and Social Science Electronic Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/hasset/'),
'https://vocabularyserver.com/hurtlex/en/suggest.php' => array('name' =>  'HurtLex: lexicon of hate words','lang'=>'English', 'url'=> 'https://vocabularyserver.com/hurtlex/en/'),
'https://vocabularyserver.com/ibe/suggest.php' => array('name' =>  'IBE Education Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ibe/'),
'https://vocabularyserver.com/icpsr/suggest.php' => array('name' =>  'ICPSR Subject Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/icpsr/'),
'https://vocabularyserver.com/ilo/suggest.php' => array('name' =>  'ILO Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ilo/'),
'https://vocabularyserver.com/instruments/suggest.php' => array('name' =>  'Instruments Tree','lang'=>'English', 'url'=> 'https://vocabularyserver.com/instruments/'),
'https://vocabularyserver.com/ipsv/suggest.php' => array('name' =>  'Integrated Public Sector Vocabulary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ipsv/'),
'https://vocabularyserver.com/ip/suggest.php' => array('name' =>  'Intellectual Property Subject Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ip/'),
'https://vocabularyserver.com/interwater/en/suggest.php' => array('name' =>  'InterWATER Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/interwater/en/'),
'https://vocabularyserver.com/mediatopic/suggest.php' => array('name' =>  'IPTC Media Topic','lang'=>'English', 'url'=> 'https://vocabularyserver.com/mediatopic/'),
'https://vocabularyserver.com/glossaries/iso25964/suggest.php' => array('name' =>  'ISO 25964-1: Thesauri for information retrieval','lang'=>'English', 'url'=> 'https://vocabularyserver.com/glossaries/iso25964/'),
'https://vocabularyserver.com/ivoat/suggest.php' => array('name' =>  'IVOAT Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ivoat/'),
'https://vocabularyserver.com/jacs/suggest.php' => array('name' =>  'Joint Academic Coding System','lang'=>'English', 'url'=> 'https://vocabularyserver.com/jacs/'),
'https://vocabularyserver.com/conole/suggest.php' => array('name' =>  'Learning activities','lang'=>'English', 'url'=> 'https://vocabularyserver.com/conole/'),
'https://vocabularyserver.com/linguistic/suggest.php' => array('name' =>  'Linguistics Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/linguistic/'),
'https://vocabularyserver.com/lgcl/suggest.php' => array('name' =>  'Local Government Category List','lang'=>'English', 'url'=> 'https://vocabularyserver.com/lgcl/'),
'https://vocabularyserver.com/lre/en/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/lre/en/'),
'https://vocabularyserver.com/mammals/suggest.php' => array('name' =>  'Mammal Species of the World','lang'=>'English', 'url'=> 'https://vocabularyserver.com/mammals/'),
'https://vocabularyserver.com/arcobjects/suggest.php' => array('name' =>  'MDA Archaeological Objects Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/arcobjects/'),
'https://vocabularyserver.com/mediaart/suggest.php' => array('name' =>  'Media Art Research Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/mediaart/'),
'https://vocabularyserver.com/music/suggest.php' => array('name' =>  'Musicmoz Music Styles','lang'=>'English', 'url'=> 'https://vocabularyserver.com/music/'),
'https://vocabularyserver.com/nasa/suggest.php' => array('name' =>  'NASA Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nasa/'),
'https://vocabularyserver.com/nal/en/suggest.php' => array('name' =>  'National Agricultural Library Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nal/en/'),
'https://vocabularyserver.com/nphl/suggest.php' => array('name' =>  'National Public Health Language','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nphl/'),
'https://vocabularyserver.com/nsm/en/suggest.php' => array('name' =>  'Natural Semantic Metalanguage','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nsm/en/'),
'https://vocabularyserver.com/netflix/suggest.php' => array('name' =>  'NetFlix Streaming Genres','lang'=>'English', 'url'=> 'https://vocabularyserver.com/netflix/'),
'https://vocabularyserver.com/nice/suggest.php' => array('name' =>  'NICE Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/nice/'),
'https://vocabularyserver.com/openscience/suggest.php' => array('name' =>  'Open Science Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/openscience/'),
'https://vocabularyserver.com/psst/suggest.php' => array('name' =>  'Peace and Security Studies Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/psst/'),
'https://vocabularyserver.com/plos/suggest.php' => array('name' =>  'PLOS  thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/plos/'),
'https://vocabularyserver.com/qb4t/suggest.php' => array('name' =>  'Queer Books for Teens controled vocabulary','lang'=>'English', 'url'=> 'https://vocabularyserver.com/qb4t/'),
'https://vocabularyserver.com/scot/suggest.php' => array('name' =>  'Schools Online Thesaurus (ScOT)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/scot/'),
'https://vocabularyserver.com/semantics/suggest.php' => array('name' =>  'Semantics','lang'=>'English', 'url'=> 'https://vocabularyserver.com/semantics/'),
'https://vocabularyserver.com/lithology/suggest.php' => array('name' =>  'SimpleLithology','lang'=>'English', 'url'=> 'https://vocabularyserver.com/lithology/'),
'https://vocabularyserver.com/cnr/ml/snowterm/en/suggest.php' => array('name' =>  'SnowTerm','lang'=>'English', 'url'=> 'https://vocabularyserver.com/cnr/ml/snowterm/en/'),
'https://vocabularyserver.com/sonz/suggest.php' => array('name' =>  'Subjects of New Zealand Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/sonz/'),
'https://vocabularyserver.com/tadirah/en/suggest.php' => array('name' =>  'TaDiRAH - Taxonomy of Digital Research Activities in the Humanities','lang'=>'English', 'url'=> 'https://vocabularyserver.com/tadirah/en/'),
'https://vocabularyserver.com/kospedia/kostax/suggest.php' => array('name' =>  'Taxonomy of KOS','lang'=>'English', 'url'=> 'https://vocabularyserver.com/kospedia/kostax/'),
'https://vocabularyserver.com/rda/suggest.php' => array('name' =>  'Term and Code List for RDA','lang'=>'English', 'url'=> 'https://vocabularyserver.com/rda/'),
'https://vocabularyserver.com/eurydice/en/suggest.php' => array('name' =>  'TESE - Thesaurus for Education Systems in Europe','lang'=>'English', 'url'=> 'https://vocabularyserver.com/eurydice/en/'),
'https://vocabularyserver.com/acm/64/suggest.php' => array('name' =>  'The 1964 ACM Computing Classification System','lang'=>'English', 'url'=> 'https://vocabularyserver.com/acm/64/'),
'https://vocabularyserver.com/acm/91/suggest.php' => array('name' =>  'The 1991 ACM Computing Classification System','lang'=>'English', 'url'=> 'https://vocabularyserver.com/acm/91/'),
'https://vocabularyserver.com/acm/98/suggest.php' => array('name' =>  'The 1998 ACM Computing Classification System','lang'=>'English', 'url'=> 'https://vocabularyserver.com/acm/98/'),
'https://vocabularyserver.com/acm/12/suggest.php' => array('name' =>  'The ACM Computing Classification System (CCS)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/acm/12/'),
'https://vocabularyserver.com/thema/en/suggest.php' => array('name' =>  'Thema – the subject category scheme for a global book trade','lang'=>'English', 'url'=> 'https://vocabularyserver.com/thema/en/'),
'https://vocabularyserver.com/psicognitive/en/suggest.php' => array('name' =>  'Thesaurus Cognitive psychology of human memory','lang'=>'English', 'url'=> 'https://vocabularyserver.com/psicognitive/en/'),
'https://vocabularyserver.com/tgm1/suggest.php' => array('name' =>  'Thesaurus for Graphic Materials 1: Subject Terms','lang'=>'English', 'url'=> 'https://vocabularyserver.com/tgm1/'),
'https://vocabularyserver.com/tgm2/suggest.php' => array('name' =>  'Thesaurus for Graphic Materials 2','lang'=>'English', 'url'=> 'https://vocabularyserver.com/tgm2/'),
'https://vocabularyserver.com/archivethesaurus/suggest.php' => array('name' =>  'Thesaurus for Use in College and University Archives','lang'=>'English', 'url'=> 'https://vocabularyserver.com/archivethesaurus/'),
'https://vocabularyserver.com/tags/suggest.php' => array('name' =>  'Thesaurus of Australian Government Subjects','lang'=>'English', 'url'=> 'https://vocabularyserver.com/tags/'),
'https://vocabularyserver.com/ficcion/en/suggest.php' => array('name' =>  'Thesaurus of fiction genres','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ficcion/en/'),
'https://vocabularyserver.com/docutes/en/suggest.php' => array('name' =>  'Thesaurus of Information Science','lang'=>'English', 'url'=> 'https://vocabularyserver.com/docutes/en/'),
'https://vocabularyserver.com/parasitology/suggest.php' => array('name' =>  'Thesaurus of Parasitology','lang'=>'English', 'url'=> 'https://vocabularyserver.com/parasitology/'),
'https://vocabularyserver.com/ttla/en/suggest.php' => array('name' =>  'Thesaurus on tourism and leisure activities','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ttla/en/'),
'https://vocabularyserver.com/pico/en/suggest.php' => array('name' =>  'Thesaurus PICO 4.1','lang'=>'English', 'url'=> 'https://vocabularyserver.com/pico/en/'),
'https://vocabularyserver.com/trt/suggest.php' => array('name' =>  'Transportation Research Thesaurus (TRT)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/trt/'),
'https://vocabularyserver.com/triblex/suggest.php' => array('name' =>  'Triblex: case-law database','lang'=>'English', 'url'=> 'https://vocabularyserver.com/triblex/'),
'https://vocabularyserver.com/ukat/suggest.php' => array('name' =>  'UK Archival Thesaurus (UKAT)','lang'=>'English', 'url'=> 'https://vocabularyserver.com/ukat/'),
'https://vocabularyserver.com/unbis/en/suggest.php' => array('name' =>  'UNBIS Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/unbis/en/'),
'https://vocabularyserver.com/unesco/en/suggest.php' => array('name' =>  'Unesco Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/unesco/en/'),
'https://vocabularyserver.com/udc/en/suggest.php' => array('name' =>  'Universal Decimal Classification','lang'=>'English', 'url'=> 'https://vocabularyserver.com/udc/en/'),
'https://vocabularyserver.com/usaid/suggest.php' => array('name' =>  'USAID  thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/usaid/'),
'https://vocabularyserver.com/shoa/suggest.php' => array('name' =>  'USC Shoah Foundation Institute Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/shoa/'),
'https://vocabularyserver.com/usgs/suggest.php' => array('name' =>  'USGS Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/usgs/'),
'https://vocabularyserver.com/utahtaxonomy/suggest.php' => array('name' =>  'Utah Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/utahtaxonomy/'),
'https://vocabularyserver.com/voced/suggest.php' => array('name' =>  'VOCED Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/voced/'),
'https://vocabularyserver.com/water/suggest.php' => array('name' =>  'Water Quality Library Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/water/'),
'https://vocabularyserver.com/worldbank/businesstaxonomy/suggest.php' => array('name' =>  'WBG Business Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/worldbank/businesstaxonomy/'),
'https://vocabularyserver.com/worldbank/taxonomy/suggest.php' => array('name' =>  'WBG Topical Taxonomy','lang'=>'English', 'url'=> 'https://vocabularyserver.com/worldbank/taxonomy/'),
'https://vocabularyserver.com/wicv/suggest.php' => array('name' =>  'Wisconsin Thesaurus','lang'=>'English', 'url'=> 'https://vocabularyserver.com/wicv/'),
'https://vocabularyserver.com/zines/suggest.php' => array('name' =>  'Zine Thesaurus of Subject Terms','lang'=>'English', 'url'=> 'https://vocabularyserver.com/zines/'),
'https://vocabularyserver.com/lre/fi/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Finnish', 'url'=> 'https://vocabularyserver.com/lre/fi/'),
'https://vocabularyserver.com/japotrad/fr/suggest.php' => array('name' =>  'EuroVoc FR','lang'=>'French', 'url'=> 'https://vocabularyserver.com/japotrad/fr/'),
'https://vocabularyserver.com/opensciencethes/fr/services.phpsuggest.php' => array('name' =>  'Thésaurus de la science ouverte','lang'=>'French', 'url'=> 'https://vocabularyserver.com/opensciencethes/fr/services.php'),
'https://vocabularyserver.com/santepsy5/services.phpsuggest.php' => array('name' =>  'Thesaurus en psychiatrie et en santé mentale (ver. 5)','lang'=>'French', 'url'=> 'https://vocabularyserver.com/santepsy5/services.php'),
'https://vocabularyserver.com/agrovoc/fr/suggest.php' => array('name' =>  'AGROVOC Thesaurus','lang'=>'French', 'url'=> 'https://vocabularyserver.com/agrovoc/fr/'),
'https://vocabularyserver.com/cofog/fr/suggest.php' => array('name' =>  'Classification des fonctions des administrations publiques (COFOG)','lang'=>'French', 'url'=> 'https://vocabularyserver.com/cofog/fr/'),
'https://vocabularyserver.com/hpmulti/fr/suggest.php' => array('name' =>  'European multilingual thesaurus on health promotion','lang'=>'French', 'url'=> 'https://vocabularyserver.com/hpmulti/fr/'),
'https://vocabularyserver.com/eurovoc/fr/suggest.php' => array('name' =>  'Eurovoc, thésaurus multilingue de l\'Union européenne','lang'=>'French', 'url'=> 'https://vocabularyserver.com/eurovoc/fr/'),
'https://vocabularyserver.com/gemet/fr/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'French', 'url'=> 'https://vocabularyserver.com/gemet/fr/'),
'https://vocabularyserver.com/glin/fr/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'French', 'url'=> 'https://vocabularyserver.com/glin/fr/'),
'https://vocabularyserver.com/lre/fr/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'French', 'url'=> 'https://vocabularyserver.com/lre/fr/'),
'https://vocabularyserver.com/eurydice/fr/suggest.php' => array('name' =>  'TESE - Thésaurus européen des systèmes éducatifs','lang'=>'French', 'url'=> 'https://vocabularyserver.com/eurydice/fr/'),
'https://vocabularyserver.com/sur/suggest.php' => array('name' =>  'Thésaurus de Coordination SUD','lang'=>'French', 'url'=> 'https://vocabularyserver.com/sur/'),
'https://vocabularyserver.com/objetsmobiliers/suggest.php' => array('name' =>  'Thésaurus de la désignation des objets mobiliers','lang'=>'French', 'url'=> 'https://vocabularyserver.com/objetsmobiliers/'),
'https://vocabularyserver.com/architectura/suggest.php' => array('name' =>  'Thésaurus de la désignation des œuvres architecturales et des espaces aménagés','lang'=>'French', 'url'=> 'https://vocabularyserver.com/architectura/'),
'https://vocabularyserver.com/ficcion/fr/suggest.php' => array('name' =>  'Thesaurus des genres fiction','lang'=>'French', 'url'=> 'https://vocabularyserver.com/ficcion/fr/'),
'https://vocabularyserver.com/ttla/fr/suggest.php' => array('name' =>  'Thesaurus du tourisme et des loisirs','lang'=>'French', 'url'=> 'https://vocabularyserver.com/ttla/fr/'),
'https://vocabularyserver.com/psychiatrie/suggest.php' => array('name' =>  'Thesaurus en psychiatrie et en santé mentale','lang'=>'French', 'url'=> 'https://vocabularyserver.com/psychiatrie/'),
'https://vocabularyserver.com/tee/fr/suggest.php' => array('name' =>  'Thesaurus européen d\'éducation','lang'=>'French', 'url'=> 'https://vocabularyserver.com/tee/fr/'),
'https://vocabularyserver.com/ettfr/suggest.php' => array('name' =>  'Thésaurus européen de la formation - TEF','lang'=>'French', 'url'=> 'https://vocabularyserver.com/ettfr/'),
'https://vocabularyserver.com/tip/suggest.php' => array('name' =>  'Thesaurus Information publique','lang'=>'French', 'url'=> 'https://vocabularyserver.com/tip/'),
'https://vocabularyserver.com/interwater/fr/suggest.php' => array('name' =>  'Thésaurus InterWATER','lang'=>'French', 'url'=> 'https://vocabularyserver.com/interwater/fr/'),
'https://vocabularyserver.com/psicognitive/fr/suggest.php' => array('name' =>  'Thésaurus Psychologie cognitive de la mémoire humaine','lang'=>'French', 'url'=> 'https://vocabularyserver.com/psicognitive/fr/'),
'https://vocabularyserver.com/unbis/fr/suggest.php' => array('name' =>  'Thésaurus UNBIS','lang'=>'French', 'url'=> 'https://vocabularyserver.com/unbis/fr/'),
'https://vocabularyserver.com/materie/suggest.php' => array('name' =>  'Thésaurus-matières','lang'=>'French', 'url'=> 'https://vocabularyserver.com/materie/'),
'https://vocabularyserver.com/unesco/fr/suggest.php' => array('name' =>  'Unesco Thesaurus','lang'=>'French', 'url'=> 'https://vocabularyserver.com/unesco/fr/'),
'https://vocabularyserver.com/tee/gl/suggest.php' => array('name' =>  'Thesaurus Europeo da Educación','lang'=>'Galician', 'url'=> 'https://vocabularyserver.com/tee/gl/'),
'https://vocabularyserver.com/hpmulti/de/suggest.php' => array('name' =>  'European multilingual thesaurus on health promotion','lang'=>'German', 'url'=> 'https://vocabularyserver.com/hpmulti/de/'),
'https://vocabularyserver.com/eurovoc/de/suggest.php' => array('name' =>  'Eurovoc, mehrsprachiger Thesaurus der Europäischen Union','lang'=>'German', 'url'=> 'https://vocabularyserver.com/eurovoc/de/'),
'https://vocabularyserver.com/glin/de/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'German', 'url'=> 'https://vocabularyserver.com/glin/de/'),
'https://vocabularyserver.com/tee/de/suggest.php' => array('name' =>  'Tesauro Europeo de la Educación','lang'=>'German', 'url'=> 'https://vocabularyserver.com/tee/de/'),
'https://vocabularyserver.com/lre/iw/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Hebrew', 'url'=> 'https://vocabularyserver.com/lre/iw/'),
'https://vocabularyserver.com/lre/hu/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Hungarian', 'url'=> 'https://vocabularyserver.com/lre/hu/'),
'https://vocabularyserver.com/cnr/ml/earth/it/suggest.php' => array('name' =>  'EARTh - Environmental Applications Reference Thesaurus','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/cnr/ml/earth/it/'),
'https://vocabularyserver.com/cnr/ml/eosterm/it/suggest.php' => array('name' =>  'EOSterm','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/cnr/ml/eosterm/it/'),
'https://vocabularyserver.com/eurovoc/it/suggest.php' => array('name' =>  'Eurovoc, il thesaurus multilingue dell\'Unione europea','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/eurovoc/it/'),
'https://vocabularyserver.com/gemet/it/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/gemet/it/'),
'https://vocabularyserver.com/glin/it/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/glin/it/'),
'https://vocabularyserver.com/hurtlex/it/suggest.php' => array('name' =>  'HurtLex: lessico di parole di odio','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/hurtlex/it/'),
'https://vocabularyserver.com/lre/it/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/lre/it/'),
'https://vocabularyserver.com/cnr/georiskvoc/suggest.php' => array('name' =>  'NHW Thesaurus','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/cnr/georiskvoc/'),
'https://vocabularyserver.com/cnr/ml/snowterm/it/suggest.php' => array('name' =>  'SnowTerm','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/cnr/ml/snowterm/it/'),
'https://vocabularyserver.com/tee/it/suggest.php' => array('name' =>  'Tesauro Europeo de la Educación','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/tee/it/'),
'https://vocabularyserver.com/eurydice/it/suggest.php' => array('name' =>  'TESE - Thesaurus europeo dei sistemi educativi','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/eurydice/it/'),
'https://vocabularyserver.com/ficcion/it/suggest.php' => array('name' =>  'Thesaurus di generi narrativi','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/ficcion/it/'),
'https://vocabularyserver.com/cnr/ml/geotermthes/it/suggest.php' => array('name' =>  'Thesaurus Geotermia','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/cnr/ml/geotermthes/it/'),
'https://vocabularyserver.com/thom/it/services.phpsuggest.php' => array('name' =>  'Thesaurus Movimento dei Focolari','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/thom/it/services.php'),
'https://vocabularyserver.com/pico/it/suggest.php' => array('name' =>  'Thesaurus PICO 4.1','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/pico/it/'),
'https://vocabularyserver.com/ttla/it/suggest.php' => array('name' =>  'Thesaurus su Turismo e Attività Ricreative','lang'=>'Italian', 'url'=> 'https://vocabularyserver.com/ttla/it/'),
'https://vocabularyserver.com/eurovoc/el/suggest.php' => array('name' =>  'Eurovoc','lang'=>'Modern Greek', 'url'=> 'https://vocabularyserver.com/eurovoc/el/'),
'https://vocabularyserver.com/gemet/el/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Modern Greek', 'url'=> 'https://vocabularyserver.com/gemet/el/'),
'https://vocabularyserver.com/lre/el/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Modern Greek', 'url'=> 'https://vocabularyserver.com/lre/el/'),
'https://vocabularyserver.com/eurovoc/pl/suggest.php' => array('name' =>  'Eurovoc, wieloj?zyczny tezaurus Unii Europejskiej','lang'=>'Polish', 'url'=> 'https://vocabularyserver.com/eurovoc/pl/'),
'https://vocabularyserver.com/gemet/pl/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Polish', 'url'=> 'https://vocabularyserver.com/gemet/pl/'),
'https://vocabularyserver.com/muldicat/pt/services.phpsuggest.php' => array('name' =>  'Dicionário multilíngue de termos e conceitos de catalogação (MulDiCat)','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/muldicat/pt/services.php'),
'https://vocabularyserver.com/mcp/services.phpsuggest.php' => array('name' =>  'Microtesauro de Contabilidade Patrimonial (MCP)','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/mcp/services.php'),
'https://vocabularyserver.com/psicoterm/pt/suggest.php' => array('name' =>  'Terminologia em Psicologia','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/psicoterm/pt/'),
'https://vocabularyserver.com/videogames/services.phpsuggest.php' => array('name' =>  'Tesauro de videogames','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/videogames/services.php'),
'https://vocabularyserver.com/tesliteratura/services.phpsuggest.php' => array('name' =>  'Tesauro sobre literatura','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tesliteratura/services.php'),
'https://vocabularyserver.com/det/pt/services.phpsuggest.php' => array('name' =>  'Thesaurus Europa Digital','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/det/pt/services.php'),
'https://vocabularyserver.com/iphan/suggest.php' => array('name' =>  'Vocabulário Controlado para a Rede de Bibliotecas do IPHAN','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/iphan/'),
'https://vocabularyserver.com/agrovoc/pt/suggest.php' => array('name' =>  'AGROVOC Thesaurus','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/agrovoc/pt/'),
'https://vocabularyserver.com/ddc/pt/suggest.php' => array('name' =>  'Classificação Decimal de Dewey (CDD)','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/ddc/pt/'),
'https://vocabularyserver.com/direitodecimal/suggest.php' => array('name' =>  'CLASSIFICAÇÃO DECIMAL DE DIREITO','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/direitodecimal/'),
'https://vocabularyserver.com/udc/pt/suggest.php' => array('name' =>  'Classificação Decimal Universal','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/udc/pt/'),
'https://vocabularyserver.com/hpmulti/pt/suggest.php' => array('name' =>  'European multilingual thesaurus on health promotion','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/hpmulti/pt/'),
'https://vocabularyserver.com/eurovoc/pt/suggest.php' => array('name' =>  'Eurovoc, thesaurus multilingue da União Europeia','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/eurovoc/pt/'),
'https://vocabularyserver.com/gemet/pt/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/gemet/pt/'),
'https://vocabularyserver.com/glin/pt/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/glin/pt/'),
'https://vocabularyserver.com/tadirah/pt/suggest.php' => array('name' =>  'TADiRAH - Taxonomia sobre Atividades Digitais de pesquisa nas Humanidades','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tadirah/pt/'),
'https://vocabularyserver.com/tbci/suggest.php' => array('name' =>  'Tesauro brasileiro de ciência da informação','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tbci/'),
'https://vocabularyserver.com/tepei/suggest.php' => array('name' =>  'Tesauro de Ética, Política e Epistemologia para Estudos de Informação','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tepei/'),
'https://vocabularyserver.com/tesauromuseus/suggest.php' => array('name' =>  'Tesauro de objetos do patrimônio cultural nos museus brasileiros','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tesauromuseus/'),
'https://vocabularyserver.com/tee/pt/suggest.php' => array('name' =>  'Tesauro Europeo de la Educación','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tee/pt/'),
'https://vocabularyserver.com/eurydice/pt/suggest.php' => array('name' =>  'TESE - Thesaurus Europeu dos Sistemas Educativos','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/eurydice/pt/'),
'https://vocabularyserver.com/thesagro/suggest.php' => array('name' =>  'THESAGRO: Thesaurus Agrícola Nacional','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/thesagro/'),
'https://vocabularyserver.com/brased/suggest.php' => array('name' =>  'Thesaurus Brasileiro da Educação','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/brased/'),
'https://vocabularyserver.com/tejut/suggest.php' => array('name' =>  'Thesaurus em Direito do Trabalho','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/tejut/'),
'https://vocabularyserver.com/direitosenado/suggest.php' => array('name' =>  'Vocabulário controlado básico do Direito','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/direitosenado/'),
'https://vocabularyserver.com/vcb/suggest.php' => array('name' =>  'VOCABULÁRIO CONTROLADO BÁSICO: VCB','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/vcb/'),
'https://vocabularyserver.com/espectaculo/suggest.php' => array('name' =>  'VOCABULÁRIO CONTROLADO PARA ARTES DO ESPETÁCULO','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/espectaculo/'),
'https://vocabularyserver.com/vocfot/suggest.php' => array('name' =>  'Vocabulário controlado para fotografia','lang'=>'Portuguese', 'url'=> 'https://vocabularyserver.com/vocfot/'),
'https://vocabularyserver.com/glin/ru/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'Russian', 'url'=> 'https://vocabularyserver.com/glin/ru/'),
'https://vocabularyserver.com/ddc/ru/suggest.php' => array('name' =>  'Десятичная классификация Дьюи','lang'=>'Russian', 'url'=> 'https://vocabularyserver.com/ddc/ru/'),
'https://vocabularyserver.com/cofog/ru/suggest.php' => array('name' =>  'Классификация функций органов государственного управления (КФОГУ)','lang'=>'Russian', 'url'=> 'https://vocabularyserver.com/cofog/ru/'),
'https://vocabularyserver.com/unesco/ru/suggest.php' => array('name' =>  'Тезаурус ЮНЕСКО','lang'=>'Russian', 'url'=> 'https://vocabularyserver.com/unesco/ru/'),
'https://vocabularyserver.com/unbis/ru/suggest.php' => array('name' =>  'Тезаурусе ЮНБИС','lang'=>'Russian', 'url'=> 'https://vocabularyserver.com/unbis/ru/'),
'https://vocabularyserver.com/icanh/suggest.php' => array('name' =>  'Banco Terminológico de Series Documentales. ICANH','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/icanh/'),
'https://vocabularyserver.com/lotbogota/suggest.php' => array('name' =>  'Banco Terminológico de Series Documentales. Lotería de Bogotá','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/lotbogota/'),
'https://vocabularyserver.com/fnc/services.php suggest.php' => array('name' =>  'Banco terminológico FNC: Fondo Pasivo Pensional','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/fnc/services.php '),
'https://vocabularyserver.com/aesco/suggest.php' => array('name' =>  'Banter AES COLOMBIA','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/aesco/'),
'https://vocabularyserver.com/alfm/suggest.php' => array('name' =>  'BANTER ALFM (Agencia Logística de las Fuerzas Militares)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/alfm/'),
'https://vocabularyserver.com/menvocab3/services.phpsuggest.php' => array('name' =>  'Banter Ministerio de Educación Nacional TRD Ver.3','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/menvocab3/services.php'),
'https://vocabularyserver.com/menvocab/services.phpsuggest.php' => array('name' =>  'Banter Ministerio de Educación Nacional TRD Ver.4','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/menvocab/services.php'),
'https://vocabularyserver.com/cajasai/services.phpsuggest.php' => array('name' =>  'BANTER_CAJASAI','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cajasai/services.php'),
'https://vocabularyserver.com/unicartagena/services.phpsuggest.php' => array('name' =>  'BANTER. INSTITUCIÓN UNIVERSITARIA MAYOR DE CARTAGENA','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/unicartagena/services.php'),
'https://vocabularyserver.com/unicolmayor/services.phpsuggest.php' => array('name' =>  'BANTER. UNIVERSIDAD COLEGIO MAYOR DE CUNDINAMARCA','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/unicolmayor/services.php'),
'https://vocabularyserver.com/ford/es/services.phpsuggest.php' => array('name' =>  'Campos de la Investigación y el Desarrollo OCDE','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ford/es/services.php'),
'https://vocabularyserver.com/clase/services.phpsuggest.php' => array('name' =>  'Clasificación en Ciencias Sociales y Humanidades (CLASE)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/clase/services.php'),
'https://vocabularyserver.com/muldicat/es/services.phpsuggest.php' => array('name' =>  'Diccionario multilingüe de términos y conceptos sobre catalogación (MulDiCat)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/muldicat/es/services.php'),
'https://vocabularyserver.com/etnoeducacion/services.phpsuggest.php' => array('name' =>  'Educación intercultural blingüe, etnoeducación e interculturalidad','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/etnoeducacion/services.php'),
'https://vocabularyserver.com/bne/encabezamientos/suggest.php' => array('name' =>  'Encabezamientos de materia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bne/encabezamientos/'),
'https://vocabularyserver.com/fnc/services.phpsuggest.php' => array('name' =>  'Fondo Pasivo Social: Banco terminológico','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/fnc/services.php'),
'https://vocabularyserver.com/bne/forma/suggest.php' => array('name' =>  'Género/Forma','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bne/forma/'),
'https://vocabularyserver.com/glosarios/carne/services.phpsuggest.php' => array('name' =>  'Glosario de la Carne Argentina','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/glosarios/carne/services.php'),
'https://vocabularyserver.com/semiocognicion/services.phpsuggest.php' => array('name' =>  'Glosario de términos relevantes en los ámbitos de la semiótica, de la biología y de las ciencias cognitivas','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/semiocognicion/services.php'),
'https://vocabularyserver.com/tgshistoriografia/suggest.php' => array('name' =>  'HISTORIOGRAFIA','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tgshistoriografia/'),
'https://vocabularyserver.com/motif/es/suggest.php' => array('name' =>  'Índice de motivos de la literatura folklórica','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/motif/es/'),
'https://vocabularyserver.com/alexandre/suggest.php' => array('name' =>  'La écfrasis en el Libro de Alexandre','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/alexandre/'),
'https://vocabularyserver.com/bnmmforma/suggest.php' => array('name' =>  'Lista de encabezamientos de género/forma','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bnmmforma/'),
'https://vocabularyserver.com/museos/suggest.php' => array('name' =>  'Lista de Términos Museológicos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/museos/'),
'https://vocabularyserver.com/materias/suggest.php' => array('name' =>  'Materias','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/materias/'),
'https://vocabularyserver.com/jel/es/services.phpsuggest.php' => array('name' =>  'Sistema de Clasificación JEL / Descriptores temáticos EconLit','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/jel/es/services.php'),
'https://vocabularyserver.com/bne/subencabezamientos/suggest.php' => array('name' =>  'Subencabezamientos de materia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bne/subencabezamientos/'),
'https://vocabularyserver.com/taxche/suggest.php' => array('name' =>  'TAXChe','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/taxche/'),
'https://vocabularyserver.com/biodanza/services.phpsuggest.php' => array('name' =>  'Tesauro de Biodanza','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/biodanza/services.php'),
'https://vocabularyserver.com/opensciencethes/es/services.phpsuggest.php' => array('name' =>  'Tesauro de ciencia abierta','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/opensciencethes/es/services.php'),
'https://vocabularyserver.com/comunicacion/services.phpsuggest.php' => array('name' =>  'Tesauro de Comunicacion Social','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/comunicacion/services.php'),
'https://vocabularyserver.com/derechosautor/services.phpsuggest.php' => array('name' =>  'Tesauro de derechos de autor','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/derechosautor/services.php'),
'https://vocabularyserver.com/ddhhcl/services.phpsuggest.php' => array('name' =>  'Tesauro de derechos humanos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ddhhcl/services.php'),
'https://vocabularyserver.com/ticu/services.phpsuggest.php' => array('name' =>  'Tesauro de infraestructura cultural universitaria','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ticu/services.php'),
'https://vocabularyserver.com/iaph/services.phpsuggest.php' => array('name' =>  'Tesauro de patrimonio histórico andaluz','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/iaph/services.php'),
'https://vocabularyserver.com/cinefunebre/services.phpsuggest.php' => array('name' =>  'Tesauro del cine y la industria audiovisual','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cinefunebre/services.php'),
'https://vocabularyserver.com/thom/es/services.phpsuggest.php' => array('name' =>  'Tesauro del Movimiento de los Focolares','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/thom/es/services.php'),
'https://vocabularyserver.com/ciafic/es/services.phpsuggest.php' => array('name' =>  'Tesauro en filosofía de la educación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ciafic/es/services.php'),
'https://vocabularyserver.com/comercio/services.phpsuggest.php' => array('name' =>  'Tesauro especializado en el área comercial','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/comercio/services.php'),
'https://vocabularyserver.com/det/es/services.phpsuggest.php' => array('name' =>  'Tesauro Europa Digital','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/det/es/services.php'),
'https://vocabularyserver.com/infancias/services.php suggest.php' => array('name' =>  'Tesauro infancias y adolescencia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/infancias/services.php '),
'https://vocabularyserver.com/telacibin/suggest.php' => array('name' =>  'Tesauro latinoamericano en ciencia bibliotecológica y de la información','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/telacibin/'),
'https://vocabularyserver.com/teothes/services.phpsuggest.php' => array('name' =>  'Tesauro Teológico Franciscano','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/teothes/services.php'),
'https://vocabularyserver.com/uce/services.phpsuggest.php' => array('name' =>  'Tesauro Universidad Central del Este','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/uce/services.php'),
'https://vocabularyserver.com/gestiondecalidad/suggest.php' => array('name' =>  'VOCABULARIO DE EVALUACIÓN Y GESTIÓN DE CALIDAD','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/gestiondecalidad/'),
'https://vocabularyserver.com/linguistica/suggest.php' => array('name' =>  'Vocabulario de linguística','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/linguistica/'),
'https://vocabularyserver.com/radiocomunicacion/M1224_1/suggest.php' => array('name' =>  'Vocabulario de términos de las telecomunicaciones móviles internacionales (IMT)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/radiocomunicacion/M1224_1/'),
'https://vocabularyserver.com/radiocomunicacion/P10_1298/suggest.php' => array('name' =>  'Vocabulario de términos sobre calidad de transmisión telefónica y aparatos telefónicos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/radiocomunicacion/P10_1298/'),
'https://vocabularyserver.com/agrovoc/es/suggest.php' => array('name' =>  'AGROVOC Thesaurus','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/agrovoc/es/'),
'https://vocabularyserver.com/idie/suggest.php' => array('name' =>  'Análisis de Vocabularios en el ámbito educativo','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/idie/'),
'https://vocabularyserver.com/artesaniasdecolombia/suggest.php' => array('name' =>  'Artesanías de Colombia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/artesaniasdecolombia/'),
'https://vocabularyserver.com/menvocab/suggest.php' => array('name' =>  'Banter Ministerio de Educación - MEN','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/menvocab/'),
'https://vocabularyserver.com/icdl/es/suggest.php' => array('name' =>  'Biblioteca Digital Internacional para Niños','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/icdl/es/'),
'https://vocabularyserver.com/bibjuridica/suggest.php' => array('name' =>  'BVJB','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bibjuridica/'),
'https://vocabularyserver.com/ceramica/suggest.php' => array('name' =>  'Ceramica','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ceramica/'),
'https://vocabularyserver.com/cofog/es/suggest.php' => array('name' =>  'Clasificación de las funciones del gobierno','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cofog/es/'),
'https://vocabularyserver.com/ddc/es/suggest.php' => array('name' =>  'Clasificación Decimal Dewey (CDD)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ddc/es/'),
'https://vocabularyserver.com/udc/es/suggest.php' => array('name' =>  'Clasificación Decimal Universal','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/udc/es/'),
'https://vocabularyserver.com/jita/es/suggest.php' => array('name' =>  'Clasificación JITA para las Ciencias da Información','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/jita/es/'),
'https://vocabularyserver.com/construccion/suggest.php' => array('name' =>  'Clasificación Unificada para la Industria de la Construcción','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/construccion/'),
'https://vocabularyserver.com/mediterraneo/suggest.php' => array('name' =>  'Culturas Euromediterráneas y de Oriente Próximo (Diccionario)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/mediterraneo/'),
'https://vocabularyserver.com/derechoenargentina/suggest.php' => array('name' =>  'Derecho en Sinónimos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/derechoenargentina/'),
'https://vocabularyserver.com/literaturador/lugarescomunes/suggest.php' => array('name' =>  'Diccionario de lugares comunes','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/literaturador/lugarescomunes/'),
'https://vocabularyserver.com/literaturador/bioy/suggest.php' => array('name' =>  'Diccionario del argentino exquisito','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/literaturador/bioy/'),
'https://vocabularyserver.com/literaturador/diablo/suggest.php' => array('name' =>  'Diccionario del diablo','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/literaturador/diablo/'),
'https://vocabularyserver.com/alianzafr/educacion/suggest.php' => array('name' =>  'educacion','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/alianzafr/educacion/'),
'https://vocabularyserver.com/hpmulti/es/suggest.php' => array('name' =>  'European multilingual thesaurus on health promotion','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/hpmulti/es/'),
'https://vocabularyserver.com/eurovoc/es/suggest.php' => array('name' =>  'EUROVOC','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/eurovoc/es/'),
'https://vocabularyserver.com/alianzafr/gastronomie/suggest.php' => array('name' =>  'Gastronomie','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/alianzafr/gastronomie/'),
'https://vocabularyserver.com/gemet/es/suggest.php' => array('name' =>  'GEMET Thesaurus','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/gemet/es/'),
'https://vocabularyserver.com/glin/es/suggest.php' => array('name' =>  'Global Legal Information Network (GLIN)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/glin/es/'),
'https://vocabularyserver.com/nalglossary/es/suggest.php' => array('name' =>  'Glosario de Términos Agrícolas','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/nalglossary/es/'),
'https://vocabularyserver.com/biblioglosario/suggest.php' => array('name' =>  'Glosario de términos bibliotecológicos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/biblioglosario/'),
'https://vocabularyserver.com/covid19/suggest.php' => array('name' =>  'Glosario sobre COVID-19 y políticas de salud','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/covid19/'),
'https://vocabularyserver.com/hdcsinfo/suggest.php' => array('name' =>  'HDCI','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/hdcsinfo/'),
'https://vocabularyserver.com/hurtlex/es/suggest.php' => array('name' =>  'HurtLex: lexico de palabras de odio','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/hurtlex/es/'),
'https://vocabularyserver.com/hcdn/suggest.php' => array('name' =>  'Información Parlamentaria - HCDN','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/hcdn/'),
'https://vocabularyserver.com/alianzafr/folclore/suggest.php' => array('name' =>  'Instrumentos folcloricos de Colombia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/alianzafr/folclore/'),
'https://vocabularyserver.com/interwater/es/suggest.php' => array('name' =>  'InterWATER Tesauro','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/interwater/es/'),
'https://vocabularyserver.com/isoc/suggest.php' => array('name' =>  'ISOC-Economía','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/isoc/'),
'https://vocabularyserver.com/politicaspublicas/suggest.php' => array('name' =>  'Lenguaje documental en Políticas Públicas del Distrito Capital','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/politicaspublicas/'),
'https://vocabularyserver.com/concepts/es/suggest.php' => array('name' =>  'Lineamientos para el análisis conceptual: glosario','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/concepts/es/'),
'https://vocabularyserver.com/encabezamientos/suggest.php' => array('name' =>  'Lista abreviada de encabezamientos de materia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/encabezamientos/'),
'https://vocabularyserver.com/clacso/suggest.php' => array('name' =>  'Lista de descriptores CLACSO','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/clacso/'),
'https://vocabularyserver.com/lem/suggest.php' => array('name' =>  'Lista de Encabezamientos de Materia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/lem/'),
'https://vocabularyserver.com/literaturainfantil/suggest.php' => array('name' =>  'Literatura Infantil Contemporánea Colombiana','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/literaturainfantil/'),
'https://vocabularyserver.com/lre/es/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/lre/es/'),
'https://vocabularyserver.com/cuib/suggest.php' => array('name' =>  'Macrotesauro Mexicano para Contenidos Educativos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cuib/'),
'https://vocabularyserver.com/materiales/suggest.php' => array('name' =>  'Materias','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/materiales/'),
'https://vocabularyserver.com/nsm/es/suggest.php' => array('name' =>  'Metalenguaje semántico natural','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/nsm/es/'),
'https://vocabularyserver.com/huridocs/suggest.php' => array('name' =>  'Micro-tesauros: una herramienta para la documentación de violaciones a los derechos humanos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/huridocs/'),
'https://vocabularyserver.com/maab/suggest.php' => array('name' =>  'Microtesauro de Antropología Andina Boliviana','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/maab/'),
'https://vocabularyserver.com/comprender/suggest.php' => array('name' =>  'MICROTESAURO EN DIDÁCTICA DE LAS CIENCIAS SOCIALES','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/comprender/'),
'https://vocabularyserver.com/uaslp/suggest.php' => array('name' =>  'Microtesauro en Política y Legislación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/uaslp/'),
'https://vocabularyserver.com/emergencias/suggest.php' => array('name' =>  'Microtesauro en Prevención y atención de emergencias de Bogotá','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/emergencias/'),
'https://vocabularyserver.com/mobiliario/suggest.php' => array('name' =>  'Mobiliario','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/mobiliario/'),
'https://vocabularyserver.com/numismatica/suggest.php' => array('name' =>  'Numismática','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/numismatica/'),
'https://vocabularyserver.com/oia/suggest.php' => array('name' =>  'Observatorio de la infancia','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/oia/'),
'https://vocabularyserver.com/siet/suggest.php' => array('name' =>  'Sistema de Información y Estadística Turística (SIET)','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/siet/'),
'https://vocabularyserver.com/tadirah/es/suggest.php' => array('name' =>  'TaDiRAH - Taxonomía sobre Actividades de investigación digital en humanidades','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tadirah/es/'),
'https://vocabularyserver.com/taxmos/suggest.php' => array('name' =>  'TaxMOS HD - Taxonomía para la investigación y difusión de la iconografía musivaria romana desde las Humanidades Digitales','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/taxmos/'),
'https://vocabularyserver.com/piupc/suggest.php' => array('name' =>  'Taxonomía PIUPC - UNAL','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/piupc/'),
'https://vocabularyserver.com/tecnicas/suggest.php' => array('name' =>  'Técnicas','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tecnicas/'),
'https://vocabularyserver.com/tesaurobac/suggest.php' => array('name' =>  'Tesauro Agropecuario Colombiano','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tesaurobac/'),
'https://vocabularyserver.com/tesaurobiblioci/suggest.php' => array('name' =>  'TESAURO CINEMATOGRAFICO','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tesaurobiblioci/'),
'https://vocabularyserver.com/archivistica/suggest.php' => array('name' =>  'Tesauro de Archivística Colombiana','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/archivistica/'),
'https://vocabularyserver.com/tbyd/suggest.php' => array('name' =>  'Tesauro de Biblioteconomía y Documentación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tbyd/'),
'https://vocabularyserver.com/docutes/es/suggest.php' => array('name' =>  'Tesauro de Ciencias de la Documentación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/docutes/es/'),
'https://vocabularyserver.com/tesamat/suggest.php' => array('name' =>  'Tesauro de Ciencias Matemáticas','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tesamat/'),
'https://vocabularyserver.com/cine/suggest.php' => array('name' =>  'Tesauro de cine','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cine/'),
'https://vocabularyserver.com/cadiz/suggest.php' => array('name' =>  'Tesauro de documentacion audiovisual','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cadiz/'),
'https://vocabularyserver.com/tes/suggest.php' => array('name' =>  'Tesauro de educación superior','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tes/'),
'https://vocabularyserver.com/floricultura/suggest.php' => array('name' =>  'Tesauro de FLORICULTURA','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/floricultura/'),
'https://vocabularyserver.com/ficcion/es/suggest.php' => array('name' =>  'Tesauro de géneros de ficción','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ficcion/es/'),
'https://vocabularyserver.com/hidrocarburos/suggest.php' => array('name' =>  'Tesauro de Hidrocarburos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/hidrocarburos/'),
'https://vocabularyserver.com/historiamujeres/suggest.php' => array('name' =>  'Tesauro de historia de las mujeres','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/historiamujeres/'),
'https://vocabularyserver.com/tina/suggest.php' => array('name' =>  'Tesauro de información de actualidad','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tina/'),
'https://vocabularyserver.com/nal/es/suggest.php' => array('name' =>  'Tesauro de la Biblioteca Nacional de Agricultura','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/nal/es/'),
'https://vocabularyserver.com/unesco/es/suggest.php' => array('name' =>  'Tesauro de la UNESCO','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/unesco/es/'),
'https://vocabularyserver.com/traces/es/suggest.php' => array('name' =>  'Tesauro de lengua y literatura','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/traces/es/'),
'https://vocabularyserver.com/rarothes/suggest.php' => array('name' =>  'Tesauro de Libro Antiguo y Raro','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/rarothes/'),
'https://vocabularyserver.com/bll/es/suggest.php' => array('name' =>  'Tesauro de linguística','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/bll/es/'),
'https://vocabularyserver.com/migraciones/suggest.php' => array('name' =>  'Tesauro de Migraciones Internacionales Contemporáneas','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/migraciones/'),
'https://vocabularyserver.com/mujeres/suggest.php' => array('name' =>  'Tesauro de mujeres','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/mujeres/'),
'https://vocabularyserver.com/psicologia/suggest.php' => array('name' =>  'Tesauro de Psicología','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/psicologia/'),
'https://vocabularyserver.com/psicothes/suggest.php' => array('name' =>  'Tesauro de Psicología Argentina','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/psicothes/'),
'https://vocabularyserver.com/turismo/suggest.php' => array('name' =>  'Tesauro de Turismo','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/turismo/'),
'https://vocabularyserver.com/ttla/es/suggest.php' => array('name' =>  'Tesauro de turismo y ocio','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ttla/es/'),
'https://vocabularyserver.com/intal/tesauro/suggest.php' => array('name' =>  'Tesauro del INTAL','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/intal/tesauro/'),
'https://vocabularyserver.com/smdh/suggest.php' => array('name' =>  'Tesauro del Sistema de Monitoreo en Derechos Humanos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/smdh/'),
'https://vocabularyserver.com/genero/suggest.php' => array('name' =>  'Tesauro especializado en filosofía, con enfoque de género','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/genero/'),
'https://vocabularyserver.com/tee/es/suggest.php' => array('name' =>  'Tesauro Europeo de la Educación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/tee/es/'),
'https://vocabularyserver.com/toponimos/suggest.php' => array('name' =>  'Tesauro Geográfico','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/toponimos/'),
'https://vocabularyserver.com/cortesupremamx/suggest.php' => array('name' =>  'Tesauro Jurídico de la Suprema Corte de Justicia de la Nación','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/cortesupremamx/'),
'https://vocabularyserver.com/espaciop/suggest.php' => array('name' =>  'Tesauro para la colección Espacio P','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/espaciop/'),
'https://vocabularyserver.com/redprodepaz/suggest.php' => array('name' =>  'Tesauro Redprodepaz','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/redprodepaz/'),
'https://vocabularyserver.com/corteidh/suggest.php' => array('name' =>  'Tesauro sobre derechos humanos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/corteidh/'),
'https://vocabularyserver.com/unbis/es/suggest.php' => array('name' =>  'Tesauro UNBIS','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/unbis/es/'),
'https://vocabularyserver.com/eurydice/es/suggest.php' => array('name' =>  'TESE - Tesauro Europeo de los Sistemas Educativos','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/eurydice/es/'),
'https://vocabularyserver.com/thema/es/suggest.php' => array('name' =>  'Thema 1.3: clasificación temática para editoriales y librerías','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/thema/es/'),
'https://vocabularyserver.com/ts/suggest.php' => array('name' =>  'Trabajo Social','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/ts/'),
'https://vocabularyserver.com/vitruvio/suggest.php' => array('name' =>  'Vitruvio','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/vitruvio/'),
'https://vocabularyserver.com/sedronar/suggest.php' => array('name' =>  'Vocabulario Controlado SEDRONAR','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/sedronar/'),
'https://vocabularyserver.com/filo/suggest.php' => array('name' =>  'Vocabulario de la Biblioteca Central de la FFyL','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/filo/'),
'https://vocabularyserver.com/carne/suggest.php' => array('name' =>  'Vocabulario de la Carne Vacuna Argentina','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/carne/'),
'https://vocabularyserver.com/vocabularioelectoral/suggest.php' => array('name' =>  'Vocabulario Electoral Argentino','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/vocabularioelectoral/'),
'https://vocabularyserver.com//tesaurojuridico/suggest.php' => array('name' =>  'Vocabulario Latinoamericano de Derecho','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com//tesaurojuridico/'),
'https://vocabularyserver.com/consumidor/suggest.php' => array('name' =>  'Vocabulario sobre Derechos de los consumidores','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/consumidor/'),
'https://vocabularyserver.com/vocabulariorse/suggest.php' => array('name' =>  'Vocabulario sobre Responsabilidad Social','lang'=>'Spanish', 'url'=> 'https://vocabularyserver.com/vocabulariorse/'),
'https://vocabularyserver.com/eurovoc/sv/suggest.php' => array('name' =>  'Eurovoc, EU:s flerspråkiga tesaurus','lang'=>'Swedish', 'url'=> 'https://vocabularyserver.com/eurovoc/sv/'),
'https://vocabularyserver.com/lre/sv/suggest.php' => array('name' =>  'LRE  thesaurus','lang'=>'Swedish', 'url'=> 'https://vocabularyserver.com/lre/sv/'),
    );

    /**
     * Find a suggest record by element ID.
     *
     * @param int|string $elementId
     * @return T3Suggest|null
     */
    public function findByElementId($elementId)
    {
        $select = $this->getSelect()->where('element_id = ?', $elementId);
        return $this->fetchObject($select);
    }

    /**
     * Get the suggest endpoints.
     *
     * @return array
     */
    public function getSuggestEndpoints()
    {
        return $this->_suggestEndpoints;
    }
}
