<?php
/**
 * Tematres Suggest
 *
 * @copyright Copyright 2025 Diego Ferreyra
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GNU GPLv3
 */

/**
 * Tematres Suggest plugin.
 *
**/
/**
 * The T3_suggests table.
 *
 * @package Omeka\Plugins\T3Suggest
 */
class Table_T3Suggest extends Omeka_Db_Table
{
    /**
     * List of some suggest endpoints available in Tematres. You can add your own vocabulary or see the the know case list of Tematres vocabularies in https://vocabularyserver.com/vocabularies/
     *
     *
     * @see https://vocabularyserver.com/vocabularies/
     */
    private $_suggestEndpoints = array(

   'https://vocabularyserver.com/glin/ar/suggest.php' => array('lang' => 'Arabic','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/ar/'),
'https://vocabularyserver.com/ddc/ar/suggest.php' => array('lang' => 'Arabic','name' => 'تصنيف ديوي العشري ','url'=> 'https://vocabularyserver.com/ddc/ar/'),
'https://vocabularyserver.com/unbis/ar/suggest.php' => array('lang' => 'Arabic','name' => 'مكنز الببليوغرافية (UNBIS) ','url'=> 'https://vocabularyserver.com/unbis/ar/'),
'https://vocabularyserver.com/tee/eu/suggest.php' => array('lang' => 'Basque','name' => 'Hezkuntzako europar tesauroaren ','url'=> 'https://vocabularyserver.com/tee/eu/'),
'https://vocabularyserver.com/eurovoc/bg/suggest.php' => array('lang' => 'Bulgarian','name'=>'Eurovoc, многоезичен речник на Европейския съюз ','url'=> 'https://vocabularyserver.com/eurovoc/bg/'),
'https://vocabularyserver.com/historia_catalunya/suggest.php' => array('lang' => 'Catalan','name' => 'Tesaurus d\'Història de Catalunya ','url'=> 'https://vocabularyserver.com/historia_catalunya/'),
'https://vocabularyserver.com/traces/ca/suggest.php' => array('lang' => 'Catalan','name' => 'Tesaurus de Llengua i Literatura ','url'=> 'https://vocabularyserver.com/traces/ca/'),
'https://vocabularyserver.com/tee/ca/suggest.php' => array('lang' => 'Catalan','name' => 'Tesaurus Europeu de l\'Educació ','url'=> 'https://vocabularyserver.com/tee/ca/'),
'https://vocabularyserver.com/gemet/cn/suggest.php' => array('lang' => 'Chinese','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/cn/'),
'https://vocabularyserver.com/sop/suggest.php' => array('lang' => 'Croatian','name' => 'Sustavi za označivanje i pretraživanje ','url'=> 'https://vocabularyserver.com/sop/'),
'https://vocabularyserver.com/eurovoc/cs/suggest.php' => array('lang' => 'Czech','name' => 'Eurovoc, mnohojazy?ný tezaurus Evropské unie ','url'=> 'https://vocabularyserver.com/eurovoc/cs/'),
'https://vocabularyserver.com/psh/cs/suggest.php' => array('lang' => 'Czech','name' => 'Polytematický strukturovaný heslá? ','url'=> 'https://vocabularyserver.com/psh/cs/'),
'https://vocabularyserver.com/eurovoc/nl/suggest.php' => array('lang' => 'Dutch','name' => 'Eurovoc, meertalige thesaurus van de Europese Unie ','url'=> 'https://vocabularyserver.com/eurovoc/nl/'),
'https://vocabularyserver.com/lre/nl/suggest.php' => array('lang' => 'Dutch','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/nl/'),
'https://vocabularyserver.com/atu/en/suggest.php' => array('lang' => 'English','name'=>'Aarne-Thompson-Uther Classification of Folk Tales ','url'=> 'https://vocabularyserver.com/atu/en/'),
'https://vocabularyserver.com/glossaries/cdd/suggest.php' => array('lang' => 'English','name'=>'Dewey Decimal Classification glossary ','url'=> 'https://vocabularyserver.com/glossaries/cdd/'),
'https://vocabularyserver.com/det/en/suggest.php' => array('lang' => 'English','name'=>'Digital Europa Thesaurus','url'=> 'https://vocabularyserver.com/det/en/'),
'https://vocabularyserver.com/ford/es/suggest.php' => array('lang' => 'English','name'=>'Fields of Research and Development classification (FORD)','url'=> 'https://vocabularyserver.com/ford/es/'),
'https://vocabularyserver.com/fastgenre/en/suggest.php' => array('lang' => 'English','name'=>'Form and Genre Headings ','url'=> 'https://vocabularyserver.com/fastgenre/en/'),
'https://vocabularyserver.com/fiaf/suggest.php' => array('lang' => 'English','name'=>'General subject headings for Film Archives ','url'=> 'https://vocabularyserver.com/fiaf/'),
'https://vocabularyserver.com/linguisticterms/suggest.php' => array('lang' => 'English','name'=>'Glossary of Linguistic Terms ','url'=> 'https://vocabularyserver.com/linguisticterms/'),
'https://vocabularyserver.com/glossaries/z3919/suggest.php' => array('lang' => 'English','name'=>'Guidelines for the Construction, Format, and Management of Monolingual Controlled Vocabularies ','url'=> 'https://vocabularyserver.com/glossaries/z3919/'),
'https://vocabularyserver.com/ieee/thesaurus/suggest.php' => array('lang' => 'English','name'=>'IEEE Thesaurus','url'=> 'https://vocabularyserver.com/ieee/thesaurus/'),
'https://vocabularyserver.com/jel/en/suggest.php' => array('lang' => 'English','name'=>'JEL Classification System / EconLit Subject Descriptors','url'=> 'https://vocabularyserver.com/jel/en/'),
'https://vocabularyserver.com/wals/en/suggest.php' => array('lang' => 'English','name'=>'Language features to cross-linguistic description (WALS)','url'=> 'https://vocabularyserver.com/wals/en/'),
'https://vocabularyserver.com/motif/en/suggest.php' => array('lang' => 'English','name'=>'Motif-Index of Folk-Literature ','url'=> 'https://vocabularyserver.com/motif/en/'),
'https://vocabularyserver.com/muldicat/en/suggest.php' => array('lang' => 'English','name'=>'Multilingual dictionary of cataloguing terms and concepts (MulDiCat)','url'=> 'https://vocabularyserver.com/muldicat/en/'),
'https://vocabularyserver.com/opensciencethes/en/suggest.php' => array('lang' => 'English','name'=>'Open science thesaurus','url'=> 'https://vocabularyserver.com/opensciencethes/en/'),
'https://vocabularyserver.com/pipfilm/suggest.php' => array('lang' => 'English','name'=>'P.I.P. Subject Headings ','url'=> 'https://vocabularyserver.com/pipfilm/'),
'https://vocabularyserver.com/physh/suggest.php' => array('lang' => 'English','name'=>'Physics Subject Headings - Physh ','url'=> 'https://vocabularyserver.com/physh/'),
'https://vocabularyserver.com/psh/en/suggest.php' => array('lang' => 'English','name'=>'Polythematic Structured Subject Heading System ','url'=> 'https://vocabularyserver.com/psh/en/'),
'https://vocabularyserver.com/acl/suggest.php' => array('lang' => 'English','name' => 'ACLearn ','url'=> 'https://vocabularyserver.com/acl/'),
'https://vocabularyserver.com/agcom/suggest.php' => array('lang' => 'English','name' => 'Agricultural Communications Thesaurus (AGCOM) ','url'=> 'https://vocabularyserver.com/agcom/'),
'https://vocabularyserver.com/agrovoc/en/suggest.php' => array('lang' => 'English','name' => 'AGROVOC Thesaurus ','url'=> 'https://vocabularyserver.com/agrovoc/en/'),
'https://vocabularyserver.com/adl/suggest.php' => array('lang' => 'English','name' => 'Alexandria Digital Library Feature Type Thesaurus ','url'=> 'https://vocabularyserver.com/adl/'),
'https://vocabularyserver.com/anaeethes/suggest.php' => array('lang' => 'English','name' => 'AnaEE Thesaurus ','url'=> 'https://vocabularyserver.com/anaeethes/'),
'https://vocabularyserver.com/animals/suggest.php' => array('lang' => 'English','name' => 'Animal Use Alternatives Thesaurus Terminology ','url'=> 'https://vocabularyserver.com/animals/'),
'https://vocabularyserver.com/apais/suggest.php' => array('lang' => 'English','name' => 'APAIS Thesaurus ','url'=> 'https://vocabularyserver.com/apais/'),
'https://vocabularyserver.com/apt/suggest.php' => array('lang' => 'English','name' => 'APT Australian Pictorial Thesaurus ','url'=> 'https://vocabularyserver.com/apt/'),
'https://vocabularyserver.com/asfa/suggest.php' => array('lang' => 'English','name' => 'Aquatic Sciences and Fisheries Thesaurus ','url'=> 'https://vocabularyserver.com/asfa/'),
'https://vocabularyserver.com/anzsrc/suggest.php' => array('lang' => 'English','name' => 'Australian and New Zealand Standard Research Classification ','url'=> 'https://vocabularyserver.com/anzsrc/'),
'https://vocabularyserver.com/agift/suggest.php' => array('lang' => 'English','name' => 'Australian Governments\' Interactive Functions Thesaurus ','url'=> 'https://vocabularyserver.com/agift/'),
'https://vocabularyserver.com/bll/en/suggest.php' => array('lang' => 'English','name' => 'Bibliography of Linguistic Literature Thesaurus ','url'=> 'https://vocabularyserver.com/bll/en/'),
'https://vocabularyserver.com/materials/suggest.php' => array('lang' => 'English','name' => 'British Museum Materials Thesaurus ','url'=> 'https://vocabularyserver.com/materials/'),
'https://vocabularyserver.com/objects/suggest.php' => array('lang' => 'English','name' => 'British Museum Object Names Theasarus ','url'=> 'https://vocabularyserver.com/objects/'),
'https://vocabularyserver.com/csps/suggest.php' => array('lang' => 'English','name' => 'Canada School of Public Service Controlled Vocabulary ','url'=> 'https://vocabularyserver.com/csps/'),
'https://vocabularyserver.com/cofog/en/suggest.php' => array('lang' => 'English','name' => 'Classification of the Functions of Government ','url'=> 'https://vocabularyserver.com/cofog/en/'),
'https://vocabularyserver.com/ko/suggest.php' => array('lang' => 'English','name' => 'Classification System for Knowledge Organization Literature ','url'=> 'https://vocabularyserver.com/ko/'),
'https://vocabularyserver.com/cso/suggest.php' => array('lang' => 'English','name' => 'Computer Science Ontology (CSO) ','url'=> 'https://vocabularyserver.com/cso/'),
'https://vocabularyserver.com/glossaries/boxesarrows/suggest.php' => array('lang' => 'English','name' => 'Controlled Vocabularies: A Glosso-Thesaurus ','url'=> 'https://vocabularyserver.com/glossaries/boxesarrows/'),
'https://vocabularyserver.com/cbdvoc/suggest.php' => array('lang' => 'English','name' => 'Convention of Biological Diversity Controlled Vocabulary ','url'=> 'https://vocabularyserver.com/cbdvoc/'),
'https://vocabularyserver.com/thomas/suggest.php' => array('lang' => 'English','name' => 'CRS Legislative Subject Terms Used in THOMAS ','url'=> 'https://vocabularyserver.com/thomas/'),
'https://vocabularyserver.com/ddc/en/suggest.php' => array('lang' => 'English','name' => 'Dewey Decimal Classification (DDC) ','url'=> 'https://vocabularyserver.com/ddc/en/'),
'https://vocabularyserver.com/dhthesaurus/suggest.php' => array('lang' => 'English','name' => 'Digital Humanities Thesaurus ','url'=> 'https://vocabularyserver.com/dhthesaurus/'),
'https://vocabularyserver.com/dtic/suggest.php' => array('lang' => 'English','name' => 'DTIC Thesaurus ','url'=> 'https://vocabularyserver.com/dtic/'),
'https://vocabularyserver.com/cnr/ml/earth/en/suggest.php' => array('lang' => 'English','name' => 'EARTh - Environmental Applications Reference Thesaurus ','url'=> 'https://vocabularyserver.com/cnr/ml/earth/en/'),
'https://vocabularyserver.com/cnr/ml/eosterm/en/suggest.php' => array('lang' => 'English','name' => 'EOSterm ','url'=> 'https://vocabularyserver.com/cnr/ml/eosterm/en/'),
'https://vocabularyserver.com/eric/suggest.php' => array('lang' => 'English','name' => 'ERIC Thesurus ','url'=> 'https://vocabularyserver.com/eric/'),
'https://vocabularyserver.com/etnography/suggest.php' => array('lang' => 'English','name' => 'Ethnographic Thesaurus ','url'=> 'https://vocabularyserver.com/etnography/'),
'https://vocabularyserver.com/tee/en/suggest.php' => array('lang' => 'English','name' => 'European Education Thesaurus ','url'=> 'https://vocabularyserver.com/tee/en/'),
'https://vocabularyserver.com/hpmulti/en/suggest.php' => array('lang' => 'English','name' => 'European multilingual thesaurus on health promotion ','url'=> 'https://vocabularyserver.com/hpmulti/en/'),
'https://vocabularyserver.com/ett/suggest.php' => array('lang' => 'English','name' => 'European Training Thesaurus - ETT ','url'=> 'https://vocabularyserver.com/ett/'),
'https://vocabularyserver.com/eurovoc/en/suggest.php' => array('lang' => 'English','name' => 'Eurovoc, the EU\'s multilingual  thesaurus','url'=> 'https://vocabularyserver.com/eurovoc/en/'),
'https://vocabularyserver.com/taxoko/suggest.php' => array('lang' => 'English','name' => 'Formal Taxonomy of Knowledge Organization ','url'=> 'https://vocabularyserver.com/taxoko/'),
'https://vocabularyserver.com/fonz/suggest.php' => array('lang' => 'English','name' => 'Functions of New Zealand Thesaurus ','url'=> 'https://vocabularyserver.com/fonz/'),
'https://vocabularyserver.com/gemet/en/suggest.php' => array('lang' => 'English','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/en/'),
'https://vocabularyserver.com/eige/suggest.php' => array('lang' => 'English','name' => 'Gender Equality Glossary and Thesaurus ','url'=> 'https://vocabularyserver.com/eige/'),
'https://vocabularyserver.com/lawgenre/suggest.php' => array('lang' => 'English','name' => 'Genre/Form Terms for Law Materials ','url'=> 'https://vocabularyserver.com/lawgenre/'),
'https://vocabularyserver.com/cnr/ml/geotermthes/en/suggest.php' => array('lang' => 'English','name' => 'Geothermal Thesaurus ','url'=> 'https://vocabularyserver.com/cnr/ml/geotermthes/en/'),
'https://vocabularyserver.com/glin/en/suggest.php' => array('lang' => 'English','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/en/'),
'https://vocabularyserver.com/glossaries/getty/suggest.php' => array('lang' => 'English','name' => 'Glossary about Controlled Vocabularies ','url'=> 'https://vocabularyserver.com/glossaries/getty/'),
'https://vocabularyserver.com/nalglossary/en/suggest.php' => array('lang' => 'English','name' => 'Glossary of Agricultural Terms ','url'=> 'https://vocabularyserver.com/nalglossary/en/'),
'https://vocabularyserver.com/glossaries/willpower/suggest.php' => array('lang' => 'English','name' => 'Glossary of terms relating to thesauri and other forms of        structured vocabulary for information retrieval ','url'=> 'https://vocabularyserver.com/glossaries/willpower/'),
'https://vocabularyserver.com/cst/suggest.php' => array('lang' => 'English','name' => 'Government of Canada Core Subject Thesaurus ','url'=> 'https://vocabularyserver.com/cst/'),
'https://vocabularyserver.com/concepts/en/suggest.php' => array('lang' => 'English','name' => 'Guidelines for concept analysis: glossary ','url'=> 'https://vocabularyserver.com/concepts/en/'),
'https://vocabularyserver.com/harrypotter/suggest.php' => array('lang' => 'English','name' => 'Harry Potter Thesaurus ','url'=> 'https://vocabularyserver.com/harrypotter/'),
'https://vocabularyserver.com/homosaurus/suggest.php' => array('lang' => 'English','name' => 'Homosaurus Vocabulary Terms ','url'=> 'https://vocabularyserver.com/homosaurus/'),
'https://vocabularyserver.com/hasset/suggest.php' => array('lang' => 'English','name' => 'Humanities and Social Science Electronic Thesaurus ','url'=> 'https://vocabularyserver.com/hasset/'),
'https://vocabularyserver.com/hurtlex/en/suggest.php' => array('lang' => 'English','name' => 'HurtLex: lexicon of hate words ','url'=> 'https://vocabularyserver.com/hurtlex/en/'),
'https://vocabularyserver.com/ibe/suggest.php' => array('lang' => 'English','name' => 'IBE Education Thesaurus ','url'=> 'https://vocabularyserver.com/ibe/'),
'https://vocabularyserver.com/icpsr/suggest.php' => array('lang' => 'English','name' => 'ICPSR Subject Thesaurus ','url'=> 'https://vocabularyserver.com/icpsr/'),
'https://vocabularyserver.com/ilo/suggest.php' => array('lang' => 'English','name' => 'ILO Thesaurus ','url'=> 'https://vocabularyserver.com/ilo/'),
'https://vocabularyserver.com/instruments/suggest.php' => array('lang' => 'English','name' => 'Instruments Tree ','url'=> 'https://vocabularyserver.com/instruments/'),
'https://vocabularyserver.com/ipsv/suggest.php' => array('lang' => 'English','name' => 'Integrated Public Sector Vocabulary ','url'=> 'https://vocabularyserver.com/ipsv/'),
'https://vocabularyserver.com/ip/suggest.php' => array('lang' => 'English','name' => 'Intellectual Property Subject Thesaurus ','url'=> 'https://vocabularyserver.com/ip/'),
'https://vocabularyserver.com/interwater/en/suggest.php' => array('lang' => 'English','name' => 'InterWATER Thesaurus ','url'=> 'https://vocabularyserver.com/interwater/en/'),
'https://vocabularyserver.com/mediatopic/suggest.php' => array('lang' => 'English','name' => 'IPTC Media Topic ','url'=> 'https://vocabularyserver.com/mediatopic/'),
'https://vocabularyserver.com/glossaries/iso25964/suggest.php' => array('lang' => 'English','name' => 'ISO 25964-1: Thesauri for information retrieval ','url'=> 'https://vocabularyserver.com/glossaries/iso25964/'),
'https://vocabularyserver.com/ivoat/suggest.php' => array('lang' => 'English','name' => 'IVOAT Thesaurus ','url'=> 'https://vocabularyserver.com/ivoat/'),
'https://vocabularyserver.com/jacs/suggest.php' => array('lang' => 'English','name' => 'Joint Academic Coding System ','url'=> 'https://vocabularyserver.com/jacs/'),
'https://vocabularyserver.com/conole/suggest.php' => array('lang' => 'English','name' => 'Learning activities ','url'=> 'https://vocabularyserver.com/conole/'),
'https://vocabularyserver.com/linguistic/suggest.php' => array('lang' => 'English','name' => 'Linguistics Thesaurus ','url'=> 'https://vocabularyserver.com/linguistic/'),
'https://vocabularyserver.com/lgcl/suggest.php' => array('lang' => 'English','name' => 'Local Government Category List ','url'=> 'https://vocabularyserver.com/lgcl/'),
'https://vocabularyserver.com/lre/en/suggest.php' => array('lang' => 'English','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/en/'),
'https://vocabularyserver.com/mammals/suggest.php' => array('lang' => 'English','name' => 'Mammal Species of the World ','url'=> 'https://vocabularyserver.com/mammals/'),
'https://vocabularyserver.com/arcobjects/suggest.php' => array('lang' => 'English','name' => 'MDA Archaeological Objects Thesaurus ','url'=> 'https://vocabularyserver.com/arcobjects/'),
'https://vocabularyserver.com/mediaart/suggest.php' => array('lang' => 'English','name' => 'Media Art Research Thesaurus ','url'=> 'https://vocabularyserver.com/mediaart/'),
'https://vocabularyserver.com/music/suggest.php' => array('lang' => 'English','name' => 'Musicmoz Music Styles ','url'=> 'https://vocabularyserver.com/music/'),
'https://vocabularyserver.com/nasa/suggest.php' => array('lang' => 'English','name' => 'NASA Taxonomy ','url'=> 'https://vocabularyserver.com/nasa/'),
'https://vocabularyserver.com/nal/en/suggest.php' => array('lang' => 'English','name' => 'National Agricultural Library Thesaurus ','url'=> 'https://vocabularyserver.com/nal/en/'),
'https://vocabularyserver.com/nphl/suggest.php' => array('lang' => 'English','name' => 'National Public Health Language ','url'=> 'https://vocabularyserver.com/nphl/'),
'https://vocabularyserver.com/nsm/en/suggest.php' => array('lang' => 'English','name' => 'Natural Semantic Metalanguage ','url'=> 'https://vocabularyserver.com/nsm/en/'),
'https://vocabularyserver.com/netflix/suggest.php' => array('lang' => 'English','name' => 'NetFlix Streaming Genres ','url'=> 'https://vocabularyserver.com/netflix/'),
'https://vocabularyserver.com/nice/suggest.php' => array('lang' => 'English','name' => 'NICE Taxonomy ','url'=> 'https://vocabularyserver.com/nice/'),
'https://vocabularyserver.com/openscience/suggest.php' => array('lang' => 'English','name' => 'Open Science Taxonomy ','url'=> 'https://vocabularyserver.com/openscience/'),
'https://vocabularyserver.com/psst/suggest.php' => array('lang' => 'English','name' => 'Peace and Security Studies Thesaurus ','url'=> 'https://vocabularyserver.com/psst/'),
'https://vocabularyserver.com/plos/suggest.php' => array('lang' => 'English','name' => 'PLOS  thesaurus','url'=> 'https://vocabularyserver.com/plos/'),
'https://vocabularyserver.com/qb4t/suggest.php' => array('lang' => 'English','name' => 'Queer Books for Teens controled vocabulary ','url'=> 'https://vocabularyserver.com/qb4t/'),
'https://vocabularyserver.com/scot/suggest.php' => array('lang' => 'English','name' => 'Schools Online Thesaurus (ScOT) ','url'=> 'https://vocabularyserver.com/scot/'),
'https://vocabularyserver.com/semantics/suggest.php' => array('lang' => 'English','name' => 'Semantics ','url'=> 'https://vocabularyserver.com/semantics/'),
'https://vocabularyserver.com/lithology/suggest.php' => array('lang' => 'English','name' => 'SimpleLithology ','url'=> 'https://vocabularyserver.com/lithology/'),
'https://vocabularyserver.com/cnr/ml/snowterm/en/suggest.php' => array('lang' => 'English','name' => 'SnowTerm ','url'=> 'https://vocabularyserver.com/cnr/ml/snowterm/en/'),
'https://vocabularyserver.com/sonz/suggest.php' => array('lang' => 'English','name' => 'Subjects of New Zealand Thesaurus ','url'=> 'https://vocabularyserver.com/sonz/'),
'https://vocabularyserver.com/tadirah/en/suggest.php' => array('lang' => 'English','name' => 'TaDiRAH - Taxonomy of Digital Research Activities in the Humanities ','url'=> 'https://vocabularyserver.com/tadirah/en/'),
'https://vocabularyserver.com/kospedia/kostax/suggest.php' => array('lang' => 'English','name' => 'Taxonomy of KOS ','url'=> 'https://vocabularyserver.com/kospedia/kostax/'),
'https://vocabularyserver.com/rda/suggest.php' => array('lang' => 'English','name' => 'Term and Code List for RDA ','url'=> 'https://vocabularyserver.com/rda/'),
'https://vocabularyserver.com/eurydice/en/suggest.php' => array('lang' => 'English','name' => 'TESE - Thesaurus for Education Systems in Europe ','url'=> 'https://vocabularyserver.com/eurydice/en/'),
'https://vocabularyserver.com/acm/64/suggest.php' => array('lang' => 'English','name' => 'The 1964 ACM Computing Classification System ','url'=> 'https://vocabularyserver.com/acm/64/'),
'https://vocabularyserver.com/acm/91/suggest.php' => array('lang' => 'English','name' => 'The 1991 ACM Computing Classification System ','url'=> 'https://vocabularyserver.com/acm/91/'),
'https://vocabularyserver.com/acm/98/suggest.php' => array('lang' => 'English','name' => 'The 1998 ACM Computing Classification System ','url'=> 'https://vocabularyserver.com/acm/98/'),
'https://vocabularyserver.com/acm/12/suggest.php' => array('lang' => 'English','name' => 'The ACM Computing Classification System (CCS) ','url'=> 'https://vocabularyserver.com/acm/12/'),
'https://vocabularyserver.com/thema/en/suggest.php' => array('lang' => 'English','name' => 'Thema – the subject category scheme for a global book trade ','url'=> 'https://vocabularyserver.com/thema/en/'),
'https://vocabularyserver.com/psicognitive/en/suggest.php' => array('lang' => 'English','name' => 'Thesaurus Cognitive psychology of human memory ','url'=> 'https://vocabularyserver.com/psicognitive/en/'),
'https://vocabularyserver.com/tgm1/suggest.php' => array('lang' => 'English','name' => 'Thesaurus for Graphic Materials 1: Subject Terms ','url'=> 'https://vocabularyserver.com/tgm1/'),
'https://vocabularyserver.com/tgm2/suggest.php' => array('lang' => 'English','name' => 'Thesaurus for Graphic Materials 2 ','url'=> 'https://vocabularyserver.com/tgm2/'),
'https://vocabularyserver.com/archivethesaurus/suggest.php' => array('lang' => 'English','name' => 'Thesaurus for Use in College and University Archives ','url'=> 'https://vocabularyserver.com/archivethesaurus/'),
'https://vocabularyserver.com/tags/suggest.php' => array('lang' => 'English','name' => 'Thesaurus of Australian Government Subjects ','url'=> 'https://vocabularyserver.com/tags/'),
'https://vocabularyserver.com/ficcion/en/suggest.php' => array('lang' => 'English','name' => 'Thesaurus of fiction genres ','url'=> 'https://vocabularyserver.com/ficcion/en/'),
'https://vocabularyserver.com/docutes/en/suggest.php' => array('lang' => 'English','name' => 'Thesaurus of Information Science ','url'=> 'https://vocabularyserver.com/docutes/en/'),
'https://vocabularyserver.com/parasitology/suggest.php' => array('lang' => 'English','name' => 'Thesaurus of Parasitology ','url'=> 'https://vocabularyserver.com/parasitology/'),
'https://vocabularyserver.com/ttla/en/suggest.php' => array('lang' => 'English','name' => 'Thesaurus on tourism and leisure activities ','url'=> 'https://vocabularyserver.com/ttla/en/'),
'https://vocabularyserver.com/pico/en/suggest.php' => array('lang' => 'English','name' => 'Thesaurus PICO 4.1 ','url'=> 'https://vocabularyserver.com/pico/en/'),
'https://vocabularyserver.com/trt/suggest.php' => array('lang' => 'English','name' => 'Transportation Research Thesaurus (TRT) ','url'=> 'https://vocabularyserver.com/trt/'),
'https://vocabularyserver.com/triblex/suggest.php' => array('lang' => 'English','name' => 'Triblex: case-law database ','url'=> 'https://vocabularyserver.com/triblex/'),
'https://vocabularyserver.com/ukat/suggest.php' => array('lang' => 'English','name' => 'UK Archival Thesaurus (UKAT) ','url'=> 'https://vocabularyserver.com/ukat/'),
'https://vocabularyserver.com/unbis/en/suggest.php' => array('lang' => 'English','name' => 'UNBIS Thesaurus ','url'=> 'https://vocabularyserver.com/unbis/en/'),
'https://vocabularyserver.com/unesco/en/suggest.php' => array('lang' => 'English','name' => 'Unesco Thesaurus ','url'=> 'https://vocabularyserver.com/unesco/en/'),
'https://vocabularyserver.com/udc/en/suggest.php' => array('lang' => 'English','name' => 'Universal Decimal Classification ','url'=> 'https://vocabularyserver.com/udc/en/'),
'https://vocabularyserver.com/usaid/suggest.php' => array('lang' => 'English','name' => 'USAID  thesaurus','url'=> 'https://vocabularyserver.com/usaid/'),
'https://vocabularyserver.com/shoa/suggest.php' => array('lang' => 'English','name' => 'USC Shoah Foundation Institute Thesaurus ','url'=> 'https://vocabularyserver.com/shoa/'),
'https://vocabularyserver.com/usgs/suggest.php' => array('lang' => 'English','name' => 'USGS Thesaurus ','url'=> 'https://vocabularyserver.com/usgs/'),
'https://vocabularyserver.com/utahtaxonomy/suggest.php' => array('lang' => 'English','name' => 'Utah Taxonomy ','url'=> 'https://vocabularyserver.com/utahtaxonomy/'),
'https://vocabularyserver.com/voced/suggest.php' => array('lang' => 'English','name' => 'VOCED Thesaurus ','url'=> 'https://vocabularyserver.com/voced/'),
'https://vocabularyserver.com/water/suggest.php' => array('lang' => 'English','name' => 'Water Quality Library Thesaurus ','url'=> 'https://vocabularyserver.com/water/'),
'https://vocabularyserver.com/worldbank/businesstaxonomy/suggest.php' => array('lang' => 'English','name' => 'WBG Business Taxonomy ','url'=> 'https://vocabularyserver.com/worldbank/businesstaxonomy/'),
'https://vocabularyserver.com/worldbank/taxonomy/suggest.php' => array('lang' => 'English','name' => 'WBG Topical Taxonomy ','url'=> 'https://vocabularyserver.com/worldbank/taxonomy/'),
'https://vocabularyserver.com/wicv/suggest.php' => array('lang' => 'English','name' => 'Wisconsin Thesaurus ','url'=> 'https://vocabularyserver.com/wicv/'),
'https://vocabularyserver.com/zines/suggest.php' => array('lang' => 'English','name' => 'Zine Thesaurus of Subject Terms ','url'=> 'https://vocabularyserver.com/zines/'),
'https://vocabularyserver.com/lre/fi/suggest.php' => array('lang' => 'Finnish','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/fi/'),
'https://vocabularyserver.com/japotrad/fr/suggest.php' => array('lang' => 'French','name'=>'EuroVoc FR ','url'=> 'https://vocabularyserver.com/japotrad/fr/'),
'https://vocabularyserver.com/opensciencethes/fr/suggest.php' => array('lang' => 'French','name'=>'Thésaurus de la science ouverte','url'=> 'https://vocabularyserver.com/opensciencethes/fr/'),
'https://vocabularyserver.com/santepsy5/suggest.php' => array('lang' => 'French','name'=>'Thesaurus en psychiatrie et en santé mentale (ver. 5)','url'=> 'https://vocabularyserver.com/santepsy5/'),
'https://vocabularyserver.com/agrovoc/fr/suggest.php' => array('lang' => 'French','name' => 'AGROVOC Thesaurus ','url'=> 'https://vocabularyserver.com/agrovoc/fr/'),
'https://vocabularyserver.com/cofog/fr/suggest.php' => array('lang' => 'French','name' => 'Classification des fonctions des administrations publiques (COFOG) ','url'=> 'https://vocabularyserver.com/cofog/fr/'),
'https://vocabularyserver.com/hpmulti/fr/suggest.php' => array('lang' => 'French','name' => 'European multilingual thesaurus on health promotion ','url'=> 'https://vocabularyserver.com/hpmulti/fr/'),
'https://vocabularyserver.com/eurovoc/fr/suggest.php' => array('lang' => 'French','name' => 'Eurovoc, thésaurus multilingue de l\'Union européenne ','url'=> 'https://vocabularyserver.com/eurovoc/fr/'),
'https://vocabularyserver.com/gemet/fr/suggest.php' => array('lang' => 'French','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/fr/'),
'https://vocabularyserver.com/glin/fr/suggest.php' => array('lang' => 'French','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/fr/'),
'https://vocabularyserver.com/lre/fr/suggest.php' => array('lang' => 'French','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/fr/'),
'https://vocabularyserver.com/eurydice/fr/suggest.php' => array('lang' => 'French','name' => 'TESE - Thésaurus européen des systèmes éducatifs ','url'=> 'https://vocabularyserver.com/eurydice/fr/'),
'https://vocabularyserver.com/sur/suggest.php' => array('lang' => 'French','name' => 'Thésaurus de Coordination SUD ','url'=> 'https://vocabularyserver.com/sur/'),
'https://vocabularyserver.com/objetsmobiliers/suggest.php' => array('lang' => 'French','name' => 'Thésaurus de la désignation des objets mobiliers ','url'=> 'https://vocabularyserver.com/objetsmobiliers/'),
'https://vocabularyserver.com/architectura/suggest.php' => array('lang' => 'French','name' => 'Thésaurus de la désignation des œuvres architecturales et des espaces aménagés ','url'=> 'https://vocabularyserver.com/architectura/'),
'https://vocabularyserver.com/ficcion/fr/suggest.php' => array('lang' => 'French','name' => 'Thesaurus des genres fiction ','url'=> 'https://vocabularyserver.com/ficcion/fr/'),
'https://vocabularyserver.com/ttla/fr/suggest.php' => array('lang' => 'French','name' => 'Thesaurus du tourisme et des loisirs ','url'=> 'https://vocabularyserver.com/ttla/fr/'),
'https://vocabularyserver.com/psychiatrie/suggest.php' => array('lang' => 'French','name' => 'Thesaurus en psychiatrie et en santé mentale ','url'=> 'https://vocabularyserver.com/psychiatrie/'),
'https://vocabularyserver.com/tee/fr/suggest.php' => array('lang' => 'French','name' => 'Thesaurus européen d\'éducation ','url'=> 'https://vocabularyserver.com/tee/fr/'),
'https://vocabularyserver.com/ettfr/suggest.php' => array('lang' => 'French','name' => 'Thésaurus européen de la formation - TEF ','url'=> 'https://vocabularyserver.com/ettfr/'),
'https://vocabularyserver.com/tip/suggest.php' => array('lang' => 'French','name' => 'Thesaurus Information publique ','url'=> 'https://vocabularyserver.com/tip/'),
'https://vocabularyserver.com/interwater/fr/suggest.php' => array('lang' => 'French','name' => 'Thésaurus InterWATER ','url'=> 'https://vocabularyserver.com/interwater/fr/'),
'https://vocabularyserver.com/psicognitive/fr/suggest.php' => array('lang' => 'French','name' => 'Thésaurus Psychologie cognitive de la mémoire humaine ','url'=> 'https://vocabularyserver.com/psicognitive/fr/'),
'https://vocabularyserver.com/unbis/fr/suggest.php' => array('lang' => 'French','name' => 'Thésaurus UNBIS ','url'=> 'https://vocabularyserver.com/unbis/fr/'),
'https://vocabularyserver.com/materie/suggest.php' => array('lang' => 'French','name' => 'Thésaurus-matières ','url'=> 'https://vocabularyserver.com/materie/'),
'https://vocabularyserver.com/unesco/fr/suggest.php' => array('lang' => 'French','name' => 'Unesco Thesaurus ','url'=> 'https://vocabularyserver.com/unesco/fr/'),
'https://vocabularyserver.com/tee/gl/suggest.php' => array('lang' => 'Galician','name' => 'Thesaurus Europeo da Educación ','url'=> 'https://vocabularyserver.com/tee/gl/'),
'https://vocabularyserver.com/hpmulti/de/suggest.php' => array('lang' => 'German','name' => 'European multilingual thesaurus on health promotion ','url'=> 'https://vocabularyserver.com/hpmulti/de/'),
'https://vocabularyserver.com/eurovoc/de/suggest.php' => array('lang' => 'German','name' => 'Eurovoc, mehrsprachiger Thesaurus der Europäischen Union ','url'=> 'https://vocabularyserver.com/eurovoc/de/'),
'https://vocabularyserver.com/glin/de/suggest.php' => array('lang' => 'German','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/de/'),
'https://vocabularyserver.com/tee/de/suggest.php' => array('lang' => 'German','name' => 'Tesauro Europeo de la Educación ','url'=> 'https://vocabularyserver.com/tee/de/'),
'https://vocabularyserver.com/lre/iw/suggest.php' => array('lang' => 'Hebrew','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/iw/'),
'https://vocabularyserver.com/lre/hu/suggest.php' => array('lang' => 'Hungarian','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/hu/'),
'https://vocabularyserver.com/cnr/ml/earth/it/suggest.php' => array('lang' => 'Italian','name' => 'EARTh - Environmental Applications Reference Thesaurus ','url'=> 'https://vocabularyserver.com/cnr/ml/earth/it/'),
'https://vocabularyserver.com/cnr/ml/eosterm/it/suggest.php' => array('lang' => 'Italian','name' => 'EOSterm ','url'=> 'https://vocabularyserver.com/cnr/ml/eosterm/it/'),
'https://vocabularyserver.com/eurovoc/it/suggest.php' => array('lang' => 'Italian','name' => 'Eurovoc, il thesaurus multilingue dell\'Unione europea ','url'=> 'https://vocabularyserver.com/eurovoc/it/'),
'https://vocabularyserver.com/gemet/it/suggest.php' => array('lang' => 'Italian','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/it/'),
'https://vocabularyserver.com/glin/it/suggest.php' => array('lang' => 'Italian','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/it/'),
'https://vocabularyserver.com/hurtlex/it/suggest.php' => array('lang' => 'Italian','name' => 'HurtLex: lessico di parole di odio ','url'=> 'https://vocabularyserver.com/hurtlex/it/'),
'https://vocabularyserver.com/lre/it/suggest.php' => array('lang' => 'Italian','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/it/'),
'https://vocabularyserver.com/cnr/georiskvoc/suggest.php' => array('lang' => 'Italian','name' => 'NHW Thesaurus ','url'=> 'https://vocabularyserver.com/cnr/georiskvoc/'),
'https://vocabularyserver.com/cnr/ml/snowterm/it/suggest.php' => array('lang' => 'Italian','name' => 'SnowTerm ','url'=> 'https://vocabularyserver.com/cnr/ml/snowterm/it/'),
'https://vocabularyserver.com/tee/it/suggest.php' => array('lang' => 'Italian','name' => 'Tesauro Europeo de la Educación ','url'=> 'https://vocabularyserver.com/tee/it/'),
'https://vocabularyserver.com/eurydice/it/suggest.php' => array('lang' => 'Italian','name' => 'TESE - Thesaurus europeo dei sistemi educativi ','url'=> 'https://vocabularyserver.com/eurydice/it/'),
'https://vocabularyserver.com/ficcion/it/suggest.php' => array('lang' => 'Italian','name' => 'Thesaurus di generi narrativi ','url'=> 'https://vocabularyserver.com/ficcion/it/'),
'https://vocabularyserver.com/cnr/ml/geotermthes/it/suggest.php' => array('lang' => 'Italian','name' => 'Thesaurus Geotermia ','url'=> 'https://vocabularyserver.com/cnr/ml/geotermthes/it/'),
'https://vocabularyserver.com/thom/it/suggest.php' => array('lang' => 'Italian','name' => 'Thesaurus Movimento dei Focolari ','url'=> 'https://vocabularyserver.com/thom/it/'),
'https://vocabularyserver.com/pico/it/suggest.php' => array('lang' => 'Italian','name' => 'Thesaurus PICO 4.1 ','url'=> 'https://vocabularyserver.com/pico/it/'),
'https://vocabularyserver.com/ttla/it/suggest.php' => array('lang' => 'Italian','name' => 'Thesaurus su Turismo e Attività Ricreative ','url'=> 'https://vocabularyserver.com/ttla/it/'),
'https://vocabularyserver.com/eurovoc/el/suggest.php' => array('lang' => 'Modern Greek','name' => 'Eurovoc ','url'=> 'https://vocabularyserver.com/eurovoc/el/'),
'https://vocabularyserver.com/gemet/el/suggest.php' => array('lang' => 'Modern Greek','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/el/'),
'https://vocabularyserver.com/lre/el/suggest.php' => array('lang' => 'Modern Greek','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/el/'),
'https://vocabularyserver.com/eurovoc/pl/suggest.php' => array('lang' => 'Polish','name' => 'Eurovoc, wieloj?zyczny tezaurus Unii Europejskiej ','url'=> 'https://vocabularyserver.com/eurovoc/pl/'),
'https://vocabularyserver.com/gemet/pl/suggest.php' => array('lang' => 'Polish','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/pl/'),
'https://vocabularyserver.com/muldicat/pt/suggest.php' => array('lang' => 'Portuguese','name'=>'Dicionário multilíngue de termos e conceitos de catalogação (MulDiCat)','url'=> 'https://vocabularyserver.com/muldicat/pt/'),
'https://vocabularyserver.com/mcp/suggest.php' => array('lang' => 'Portuguese','name'=>'Microtesauro de Contabilidade Patrimonial (MCP)','url'=> 'https://vocabularyserver.com/mcp/'),
'https://vocabularyserver.com/psicoterm/pt/suggest.php' => array('lang' => 'Portuguese','name'=>'Terminologia em Psicologia','url'=> 'https://vocabularyserver.com/psicoterm/pt/'),
'https://vocabularyserver.com/videogames/suggest.php' => array('lang' => 'Portuguese','name'=>'Tesauro de videogames','url'=> 'https://vocabularyserver.com/videogames/'),
'https://vocabularyserver.com/tesliteratura/suggest.php' => array('lang' => 'Portuguese','name'=>'Tesauro sobre literatura','url'=> 'https://vocabularyserver.com/tesliteratura/'),
'https://vocabularyserver.com/det/pt/suggest.php' => array('lang' => 'Portuguese','name'=>'Thesaurus Europa Digital','url'=> 'https://vocabularyserver.com/det/pt/'),
'https://vocabularyserver.com/iphan/suggest.php' => array('lang' => 'Portuguese','name'=>'Vocabulário Controlado para a Rede de Bibliotecas do IPHAN ','url'=> 'https://vocabularyserver.com/iphan/'),
'https://vocabularyserver.com/agrovoc/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'AGROVOC Thesaurus ','url'=> 'https://vocabularyserver.com/agrovoc/pt/'),
'https://vocabularyserver.com/ddc/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'Classificação Decimal de Dewey (CDD) ','url'=> 'https://vocabularyserver.com/ddc/pt/'),
'https://vocabularyserver.com/direitodecimal/suggest.php' => array('lang' => 'Portuguese','name' => 'CLASSIFICAÇÃO DECIMAL DE DIREITO ','url'=> 'https://vocabularyserver.com/direitodecimal/'),
'https://vocabularyserver.com/udc/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'Classificação Decimal Universal ','url'=> 'https://vocabularyserver.com/udc/pt/'),
'https://vocabularyserver.com/hpmulti/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'European multilingual thesaurus on health promotion ','url'=> 'https://vocabularyserver.com/hpmulti/pt/'),
'https://vocabularyserver.com/eurovoc/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'Eurovoc, thesaurus multilingue da União Europeia ','url'=> 'https://vocabularyserver.com/eurovoc/pt/'),
'https://vocabularyserver.com/gemet/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/pt/'),
'https://vocabularyserver.com/glin/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/pt/'),
'https://vocabularyserver.com/tadirah/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'TADiRAH - Taxonomia sobre Atividades Digitais de pesquisa nas Humanidades ','url'=> 'https://vocabularyserver.com/tadirah/pt/'),
'https://vocabularyserver.com/tbci/suggest.php' => array('lang' => 'Portuguese','name' => 'Tesauro brasileiro de ciência da informação ','url'=> 'https://vocabularyserver.com/tbci/'),
'https://vocabularyserver.com/tepei/suggest.php' => array('lang' => 'Portuguese','name' => 'Tesauro de Ética, Política e Epistemologia para Estudos de Informação ','url'=> 'https://vocabularyserver.com/tepei/'),
'https://vocabularyserver.com/tesauromuseus/suggest.php' => array('lang' => 'Portuguese','name' => 'Tesauro de objetos do patrimônio cultural nos museus brasileiros ','url'=> 'https://vocabularyserver.com/tesauromuseus/'),
'https://vocabularyserver.com/tee/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'Tesauro Europeo de la Educación ','url'=> 'https://vocabularyserver.com/tee/pt/'),
'https://vocabularyserver.com/eurydice/pt/suggest.php' => array('lang' => 'Portuguese','name' => 'TESE - Thesaurus Europeu dos Sistemas Educativos ','url'=> 'https://vocabularyserver.com/eurydice/pt/'),
'https://vocabularyserver.com/thesagro/suggest.php' => array('lang' => 'Portuguese','name' => 'THESAGRO: Thesaurus Agrícola Nacional ','url'=> 'https://vocabularyserver.com/thesagro/'),
'https://vocabularyserver.com/brased/suggest.php' => array('lang' => 'Portuguese','name' => 'Thesaurus Brasileiro da Educação ','url'=> 'https://vocabularyserver.com/brased/'),
'https://vocabularyserver.com/tejut/suggest.php' => array('lang' => 'Portuguese','name' => 'Thesaurus em Direito do Trabalho ','url'=> 'https://vocabularyserver.com/tejut/'),
'https://vocabularyserver.com/direitosenado/suggest.php' => array('lang' => 'Portuguese','name' => 'Vocabulário controlado básico do Direito ','url'=> 'https://vocabularyserver.com/direitosenado/'),
'https://vocabularyserver.com/vcb/suggest.php' => array('lang' => 'Portuguese','name' => 'VOCABULÁRIO CONTROLADO BÁSICO: VCB ','url'=> 'https://vocabularyserver.com/vcb/'),
'https://vocabularyserver.com/espectaculo/suggest.php' => array('lang' => 'Portuguese','name' => 'VOCABULÁRIO CONTROLADO PARA ARTES DO ESPETÁCULO ','url'=> 'https://vocabularyserver.com/espectaculo/'),
'https://vocabularyserver.com/vocfot/suggest.php' => array('lang' => 'Portuguese','name' => 'Vocabulário controlado para fotografia ','url'=> 'https://vocabularyserver.com/vocfot/'),
'https://vocabularyserver.com/glin/ru/suggest.php' => array('lang' => 'Russian','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/ru/'),
'https://vocabularyserver.com/ddc/ru/suggest.php' => array('lang' => 'Russian','name' => 'Десятичная классификация Дьюи ','url'=> 'https://vocabularyserver.com/ddc/ru/'),
'https://vocabularyserver.com/cofog/ru/suggest.php' => array('lang' => 'Russian','name' => 'Классификация функций органов государственного управления (КФОГУ) ','url'=> 'https://vocabularyserver.com/cofog/ru/'),
'https://vocabularyserver.com/unesco/ru/suggest.php' => array('lang' => 'Russian','name' => 'Тезаурус ЮНЕСКО ','url'=> 'https://vocabularyserver.com/unesco/ru/'),
'https://vocabularyserver.com/unbis/ru/suggest.php' => array('lang' => 'Russian','name' => 'Тезаурусе ЮНБИС ','url'=> 'https://vocabularyserver.com/unbis/ru/'),
'https://vocabularyserver.com/icanh/suggest.php' => array('lang' => 'Spanish','name'=>'Banco Terminológico de Series Documentales. ICANH ','url'=> 'https://vocabularyserver.com/icanh/'),
'https://vocabularyserver.com/lotbogota/suggest.php' => array('lang' => 'Spanish','name'=>'Banco Terminológico de Series Documentales. Lotería de Bogotá ','url'=> 'https://vocabularyserver.com/lotbogota/'),
'https://vocabularyserver.com/fnc/suggest.php' => array('lang' => 'Spanish','name'=>'Banco terminológico FNC: Fondo Pasivo Pensional','url'=> 'https://vocabularyserver.com/fnc/'),
'https://vocabularyserver.com/aesco/suggest.php' => array('lang' => 'Spanish','name'=>'Banter AES COLOMBIA ','url'=> 'https://vocabularyserver.com/aesco/'),
'https://vocabularyserver.com/alfm/suggest.php' => array('lang' => 'Spanish','name'=>'BANTER ALFM (Agencia Logística de las Fuerzas Militares) ','url'=> 'https://vocabularyserver.com/alfm/'),
'https://vocabularyserver.com/menvocab3/suggest.php' => array('lang' => 'Spanish','name'=>'Banter Ministerio de Educación Nacional TRD Ver.3','url'=> 'https://vocabularyserver.com/menvocab3/'),
'https://vocabularyserver.com/menvocab/suggest.php' => array('lang' => 'Spanish','name'=>'Banter Ministerio de Educación Nacional TRD Ver.4','url'=> 'https://vocabularyserver.com/menvocab/'),
'https://vocabularyserver.com/cajasai/suggest.php' => array('lang' => 'Spanish','name'=>'BANTER_CAJASAI','url'=> 'https://vocabularyserver.com/cajasai/'),
'https://vocabularyserver.com/unicartagena/suggest.php' => array('lang' => 'Spanish','name'=>'BANTER. INSTITUCIÓN UNIVERSITARIA MAYOR DE CARTAGENA','url'=> 'https://vocabularyserver.com/unicartagena/'),
'https://vocabularyserver.com/unicolmayor/suggest.php' => array('lang' => 'Spanish','name'=>'BANTER. UNIVERSIDAD COLEGIO MAYOR DE CUNDINAMARCA','url'=> 'https://vocabularyserver.com/unicolmayor/'),
'https://vocabularyserver.com/ford/es/suggest.php' => array('lang' => 'Spanish','name'=>'Campos de la Investigación y el Desarrollo OCDE','url'=> 'https://vocabularyserver.com/ford/es/'),
'https://vocabularyserver.com/cineabyayala/suggest.php' => array('lang' => 'Spanish','name' => 'Festivales de Cine Indígena de Abya Yala','url'=> 'https://vocabularyserver.com/cineabyayala/'),
'https://vocabularyserver.com/clase/suggest.php' => array('lang' => 'Spanish','name'=>'Clasificación en Ciencias Sociales y Humanidades (CLASE)','url'=> 'https://vocabularyserver.com/clase/'),
'https://vocabularyserver.com/muldicat/es/suggest.php' => array('lang' => 'Spanish','name'=>'Diccionario multilingüe de términos y conceptos sobre catalogación (MulDiCat)','url'=> 'https://vocabularyserver.com/muldicat/es/'),
'https://vocabularyserver.com/etnoeducacion/suggest.php' => array('lang' => 'Spanish','name'=>'Educación intercultural blingüe, etnoeducación e interculturalidad','url'=> 'https://vocabularyserver.com/etnoeducacion/'),
'https://vocabularyserver.com/bne/encabezamientos/suggest.php' => array('lang' => 'Spanish','name'=>'Encabezamientos de materia ','url'=> 'https://vocabularyserver.com/bne/encabezamientos/'),
'https://vocabularyserver.com/fnc/suggest.php' => array('lang' => 'Spanish','name'=>'Fondo Pasivo Social: Banco terminológico','url'=> 'https://vocabularyserver.com/fnc/'),
'https://vocabularyserver.com/bne/forma/suggest.php' => array('lang' => 'Spanish','name'=>'Género/Forma ','url'=> 'https://vocabularyserver.com/bne/forma/'),
'https://vocabularyserver.com/glosarios/carne/suggest.php' => array('lang' => 'Spanish','name'=>'Glosario de la Carne Argentina','url'=> 'https://vocabularyserver.com/glosarios/carne/'),
'https://vocabularyserver.com/semiocognicion/suggest.php' => array('lang' => 'Spanish','name'=>'Glosario de términos relevantes en los ámbitos de la semiótica, de la biología y de las ciencias cognitivas','url'=> 'https://vocabularyserver.com/semiocognicion/'),
'https://vocabularyserver.com/tgshistoriografia/suggest.php' => array('lang' => 'Spanish','name'=>'HISTORIOGRAFIA ','url'=> 'https://vocabularyserver.com/tgshistoriografia/'),
'https://vocabularyserver.com/motif/es/suggest.php' => array('lang' => 'Spanish','name'=>'Índice de motivos de la literatura folklórica ','url'=> 'https://vocabularyserver.com/motif/es/'),
'https://vocabularyserver.com/alexandre/suggest.php' => array('lang' => 'Spanish','name'=>'La écfrasis en el Libro de Alexandre ','url'=> 'https://vocabularyserver.com/alexandre/'),
'https://vocabularyserver.com/bnmmforma/suggest.php' => array('lang' => 'Spanish','name'=>'Lista de encabezamientos de género/forma ','url'=> 'https://vocabularyserver.com/bnmmforma/'),
'https://vocabularyserver.com/museos/suggest.php' => array('lang' => 'Spanish','name'=>'Lista de Términos Museológicos ','url'=> 'https://vocabularyserver.com/museos/'),
'https://vocabularyserver.com/materias/suggest.php' => array('lang' => 'Spanish','name'=>'Materias ','url'=> 'https://vocabularyserver.com/materias/'),
'https://vocabularyserver.com/jel/es/suggest.php' => array('lang' => 'Spanish','name'=>'Sistema de Clasificación JEL / Descriptores temáticos EconLit','url'=> 'https://vocabularyserver.com/jel/es/'),
'https://vocabularyserver.com/bne/subencabezamientos/suggest.php' => array('lang' => 'Spanish','name'=>'Subencabezamientos de materia ','url'=> 'https://vocabularyserver.com/bne/subencabezamientos/'),
'https://vocabularyserver.com/taxche/suggest.php' => array('lang' => 'Spanish','name'=>'TAXChe ','url'=> 'https://vocabularyserver.com/taxche/'),
'https://vocabularyserver.com/biodanza/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de Biodanza','url'=> 'https://vocabularyserver.com/biodanza/'),
'https://vocabularyserver.com/opensciencethes/es/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de ciencia abierta','url'=> 'https://vocabularyserver.com/opensciencethes/es/'),
'https://vocabularyserver.com/comunicacion/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de Comunicacion Social','url'=> 'https://vocabularyserver.com/comunicacion/'),
'https://vocabularyserver.com/derechosautor/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de derechos de autor','url'=> 'https://vocabularyserver.com/derechosautor/'),
'https://vocabularyserver.com/ddhhcl/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de derechos humanos','url'=> 'https://vocabularyserver.com/ddhhcl/'),
'https://vocabularyserver.com/ticu/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de infraestructura cultural universitaria','url'=> 'https://vocabularyserver.com/ticu/'),
'https://vocabularyserver.com/iaph/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro de patrimonio histórico andaluz','url'=> 'https://vocabularyserver.com/iaph/'),
'https://vocabularyserver.com/cinefunebre/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro del cine y la industria audiovisual','url'=> 'https://vocabularyserver.com/cinefunebre/'),
'https://vocabularyserver.com/thom/es/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro del Movimiento de los Focolares','url'=> 'https://vocabularyserver.com/thom/es/'),
'https://vocabularyserver.com/ciafic/es/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro en filosofía de la educación','url'=> 'https://vocabularyserver.com/ciafic/es/'),
'https://vocabularyserver.com/comercio/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro especializado en el área comercial','url'=> 'https://vocabularyserver.com/comercio/'),
'https://vocabularyserver.com/det/es/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro Europa Digital','url'=> 'https://vocabularyserver.com/det/es/'),
'https://vocabularyserver.com/infancias/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro infancias y adolescencia','url'=> 'https://vocabularyserver.com/infancias/'),
'https://vocabularyserver.com/telacibin/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro latinoamericano en ciencia bibliotecológica y de la información ','url'=> 'https://vocabularyserver.com/telacibin/'),
'https://vocabularyserver.com/teothes/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro Teológico Franciscano','url'=> 'https://vocabularyserver.com/teothes/'),
'https://vocabularyserver.com/uce/suggest.php' => array('lang' => 'Spanish','name'=>'Tesauro Universidad Central del Este','url'=> 'https://vocabularyserver.com/uce/'),
'https://vocabularyserver.com/gestiondecalidad/suggest.php' => array('lang' => 'Spanish','name'=>'VOCABULARIO DE EVALUACIÓN Y GESTIÓN DE CALIDAD ','url'=> 'https://vocabularyserver.com/gestiondecalidad/'),
'https://vocabularyserver.com/linguistica/suggest.php' => array('lang' => 'Spanish','name'=>'Vocabulario de linguística ','url'=> 'https://vocabularyserver.com/linguistica/'),
'https://vocabularyserver.com/radiocomunicacion/M1224_1/suggest.php' => array('lang' => 'Spanish','name'=>'Vocabulario de términos de las telecomunicaciones móviles internacionales (IMT) ','url'=> 'https://vocabularyserver.com/radiocomunicacion/M1224_1/'),
'https://vocabularyserver.com/radiocomunicacion/P10_1298/suggest.php' => array('lang' => 'Spanish','name'=>'Vocabulario de términos sobre calidad de transmisión telefónica y aparatos telefónicos ','url'=> 'https://vocabularyserver.com/radiocomunicacion/P10_1298/'),
'https://vocabularyserver.com/agrovoc/es/suggest.php' => array('lang' => 'Spanish','name' => 'AGROVOC Thesaurus ','url'=> 'https://vocabularyserver.com/agrovoc/es/'),
'https://vocabularyserver.com/idie/suggest.php' => array('lang' => 'Spanish','name' => 'Análisis de Vocabularios en el ámbito educativo ','url'=> 'https://vocabularyserver.com/idie/'),
'https://vocabularyserver.com/artesaniasdecolombia/suggest.php' => array('lang' => 'Spanish','name' => 'Artesanías de Colombia ','url'=> 'https://vocabularyserver.com/artesaniasdecolombia/'),
'https://vocabularyserver.com/menvocab/suggest.php' => array('lang' => 'Spanish','name' => 'Banter Ministerio de Educación - MEN ','url'=> 'https://vocabularyserver.com/menvocab/'),
'https://vocabularyserver.com/icdl/es/suggest.php' => array('lang' => 'Spanish','name' => 'Biblioteca Digital Internacional para Niños ','url'=> 'https://vocabularyserver.com/icdl/es/'),
'https://vocabularyserver.com/bibjuridica/suggest.php' => array('lang' => 'Spanish','name' => 'BVJB ','url'=> 'https://vocabularyserver.com/bibjuridica/'),
'https://vocabularyserver.com/ceramica/suggest.php' => array('lang' => 'Spanish','name' => 'Ceramica ','url'=> 'https://vocabularyserver.com/ceramica/'),
'https://vocabularyserver.com/cofog/es/suggest.php' => array('lang' => 'Spanish','name' => 'Clasificación de las funciones del gobierno ','url'=> 'https://vocabularyserver.com/cofog/es/'),
'https://vocabularyserver.com/ddc/es/suggest.php' => array('lang' => 'Spanish','name' => 'Clasificación Decimal Dewey (CDD) ','url'=> 'https://vocabularyserver.com/ddc/es/'),
'https://vocabularyserver.com/udc/es/suggest.php' => array('lang' => 'Spanish','name' => 'Clasificación Decimal Universal ','url'=> 'https://vocabularyserver.com/udc/es/'),
'https://vocabularyserver.com/jita/es/suggest.php' => array('lang' => 'Spanish','name' => 'Clasificación JITA para las Ciencias da Información ','url'=> 'https://vocabularyserver.com/jita/es/'),
'https://vocabularyserver.com/construccion/suggest.php' => array('lang' => 'Spanish','name' => 'Clasificación Unificada para la Industria de la Construcción ','url'=> 'https://vocabularyserver.com/construccion/'),
'https://vocabularyserver.com/mediterraneo/suggest.php' => array('lang' => 'Spanish','name' => 'Culturas Euromediterráneas y de Oriente Próximo (Diccionario) ','url'=> 'https://vocabularyserver.com/mediterraneo/'),
'https://vocabularyserver.com/derechoenargentina/suggest.php' => array('lang' => 'Spanish','name' => 'Derecho en Sinónimos ','url'=> 'https://vocabularyserver.com/derechoenargentina/'),
'https://vocabularyserver.com/literaturador/lugarescomunes/suggest.php' => array('lang' => 'Spanish','name' => 'Diccionario de lugares comunes ','url'=> 'https://vocabularyserver.com/literaturador/lugarescomunes/'),
'https://vocabularyserver.com/literaturador/bioy/suggest.php' => array('lang' => 'Spanish','name' => 'Diccionario del argentino exquisito ','url'=> 'https://vocabularyserver.com/literaturador/bioy/'),
'https://vocabularyserver.com/literaturador/diablo/suggest.php' => array('lang' => 'Spanish','name' => 'Diccionario del diablo ','url'=> 'https://vocabularyserver.com/literaturador/diablo/'),
'https://vocabularyserver.com/alianzafr/educacion/suggest.php' => array('lang' => 'Spanish','name' => 'educacion ','url'=> 'https://vocabularyserver.com/alianzafr/educacion/'),
'https://vocabularyserver.com/hpmulti/es/suggest.php' => array('lang' => 'Spanish','name' => 'European multilingual thesaurus on health promotion ','url'=> 'https://vocabularyserver.com/hpmulti/es/'),
'https://vocabularyserver.com/eurovoc/es/suggest.php' => array('lang' => 'Spanish','name' => 'EUROVOC ','url'=> 'https://vocabularyserver.com/eurovoc/es/'),
'https://vocabularyserver.com/alianzafr/gastronomie/suggest.php' => array('lang' => 'Spanish','name' => 'Gastronomie ','url'=> 'https://vocabularyserver.com/alianzafr/gastronomie/'),
'https://vocabularyserver.com/gemet/es/suggest.php' => array('lang' => 'Spanish','name' => 'GEMET Thesaurus ','url'=> 'https://vocabularyserver.com/gemet/es/'),
'https://vocabularyserver.com/glin/es/suggest.php' => array('lang' => 'Spanish','name' => 'Global Legal Information Network (GLIN) ','url'=> 'https://vocabularyserver.com/glin/es/'),
'https://vocabularyserver.com/nalglossary/es/suggest.php' => array('lang' => 'Spanish','name' => 'Glosario de Términos Agrícolas ','url'=> 'https://vocabularyserver.com/nalglossary/es/'),
'https://vocabularyserver.com/biblioglosario/suggest.php' => array('lang' => 'Spanish','name' => 'Glosario de términos bibliotecológicos ','url'=> 'https://vocabularyserver.com/biblioglosario/'),
'https://vocabularyserver.com/covid19/suggest.php' => array('lang' => 'Spanish','name' => 'Glosario sobre COVID-19 y políticas de salud ','url'=> 'https://vocabularyserver.com/covid19/'),
'https://vocabularyserver.com/hdcsinfo/suggest.php' => array('lang' => 'Spanish','name' => 'HDCI ','url'=> 'https://vocabularyserver.com/hdcsinfo/'),
'https://vocabularyserver.com/hurtlex/es/suggest.php' => array('lang' => 'Spanish','name' => 'HurtLex: lexico de palabras de odio ','url'=> 'https://vocabularyserver.com/hurtlex/es/'),
'https://vocabularyserver.com/hcdn/suggest.php' => array('lang' => 'Spanish','name' => 'Información Parlamentaria - HCDN ','url'=> 'https://vocabularyserver.com/hcdn/'),
'https://vocabularyserver.com/alianzafr/folclore/suggest.php' => array('lang' => 'Spanish','name' => 'Instrumentos folcloricos de Colombia ','url'=> 'https://vocabularyserver.com/alianzafr/folclore/'),
'https://vocabularyserver.com/interwater/es/suggest.php' => array('lang' => 'Spanish','name' => 'InterWATER Tesauro ','url'=> 'https://vocabularyserver.com/interwater/es/'),
'https://vocabularyserver.com/isoc/suggest.php' => array('lang' => 'Spanish','name' => 'ISOC-Economía ','url'=> 'https://vocabularyserver.com/isoc/'),
'https://vocabularyserver.com/politicaspublicas/suggest.php' => array('lang' => 'Spanish','name' => 'Lenguaje documental en Políticas Públicas del Distrito Capital ','url'=> 'https://vocabularyserver.com/politicaspublicas/'),
'https://vocabularyserver.com/concepts/es/suggest.php' => array('lang' => 'Spanish','name' => 'Lineamientos para el análisis conceptual: glosario ','url'=> 'https://vocabularyserver.com/concepts/es/'),
'https://vocabularyserver.com/encabezamientos/suggest.php' => array('lang' => 'Spanish','name' => 'Lista abreviada de encabezamientos de materia ','url'=> 'https://vocabularyserver.com/encabezamientos/'),
'https://vocabularyserver.com/clacso/suggest.php' => array('lang' => 'Spanish','name' => 'Lista de descriptores CLACSO ','url'=> 'https://vocabularyserver.com/clacso/'),
'https://vocabularyserver.com/lem/suggest.php' => array('lang' => 'Spanish','name' => 'Lista de Encabezamientos de Materia ','url'=> 'https://vocabularyserver.com/lem/'),
'https://vocabularyserver.com/literaturainfantil/suggest.php' => array('lang' => 'Spanish','name' => 'Literatura Infantil Contemporánea Colombiana ','url'=> 'https://vocabularyserver.com/literaturainfantil/'),
'https://vocabularyserver.com/lre/es/suggest.php' => array('lang' => 'Spanish','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/es/'),
'https://vocabularyserver.com/cuib/suggest.php' => array('lang' => 'Spanish','name' => 'Macrotesauro Mexicano para Contenidos Educativos ','url'=> 'https://vocabularyserver.com/cuib/'),
'https://vocabularyserver.com/materiales/suggest.php' => array('lang' => 'Spanish','name' => 'Materias ','url'=> 'https://vocabularyserver.com/materiales/'),
'https://vocabularyserver.com/nsm/es/suggest.php' => array('lang' => 'Spanish','name' => 'Metalenguaje semántico natural ','url'=> 'https://vocabularyserver.com/nsm/es/'),
'https://vocabularyserver.com/huridocs/suggest.php' => array('lang' => 'Spanish','name' => 'Micro-tesauros: una herramienta para la documentación de violaciones a los derechos humanos ','url'=> 'https://vocabularyserver.com/huridocs/'),
'https://vocabularyserver.com/maab/suggest.php' => array('lang' => 'Spanish','name' => 'Microtesauro de Antropología Andina Boliviana ','url'=> 'https://vocabularyserver.com/maab/'),
'https://vocabularyserver.com/comprender/suggest.php' => array('lang' => 'Spanish','name' => 'MICROTESAURO EN DIDÁCTICA DE LAS CIENCIAS SOCIALES ','url'=> 'https://vocabularyserver.com/comprender/'),
'https://vocabularyserver.com/uaslp/suggest.php' => array('lang' => 'Spanish','name' => 'Microtesauro en Política y Legislación ','url'=> 'https://vocabularyserver.com/uaslp/'),
'https://vocabularyserver.com/emergencias/suggest.php' => array('lang' => 'Spanish','name' => 'Microtesauro en Prevención y atención de emergencias de Bogotá ','url'=> 'https://vocabularyserver.com/emergencias/'),
'https://vocabularyserver.com/mobiliario/suggest.php' => array('lang' => 'Spanish','name' => 'Mobiliario ','url'=> 'https://vocabularyserver.com/mobiliario/'),
'https://vocabularyserver.com/numismatica/suggest.php' => array('lang' => 'Spanish','name' => 'Numismática ','url'=> 'https://vocabularyserver.com/numismatica/'),
'https://vocabularyserver.com/oia/suggest.php' => array('lang' => 'Spanish','name' => 'Observatorio de la infancia ','url'=> 'https://vocabularyserver.com/oia/'),
'https://vocabularyserver.com/siet/suggest.php' => array('lang' => 'Spanish','name' => 'Sistema de Información y Estadística Turística (SIET) ','url'=> 'https://vocabularyserver.com/siet/'),
'https://vocabularyserver.com/tadirah/es/suggest.php' => array('lang' => 'Spanish','name' => 'TaDiRAH - Taxonomía sobre Actividades de investigación digital en humanidades ','url'=> 'https://vocabularyserver.com/tadirah/es/'),
'https://vocabularyserver.com/taxmos/suggest.php' => array('lang' => 'Spanish','name' => 'TaxMOS HD - Taxonomía para la investigación y difusión de la iconografía musivaria romana desde las Humanidades Digitales ','url'=> 'https://vocabularyserver.com/taxmos/'),
'https://vocabularyserver.com/piupc/suggest.php' => array('lang' => 'Spanish','name' => 'Taxonomía PIUPC - UNAL ','url'=> 'https://vocabularyserver.com/piupc/'),
'https://vocabularyserver.com/tecnicas/suggest.php' => array('lang' => 'Spanish','name' => 'Técnicas ','url'=> 'https://vocabularyserver.com/tecnicas/'),
'https://vocabularyserver.com/tesaurobac/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro Agropecuario Colombiano ','url'=> 'https://vocabularyserver.com/tesaurobac/'),
'https://vocabularyserver.com/tesaurobiblioci/suggest.php' => array('lang' => 'Spanish','name' => 'TESAURO CINEMATOGRAFICO ','url'=> 'https://vocabularyserver.com/tesaurobiblioci/'),
'https://vocabularyserver.com/archivistica/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Archivística Colombiana ','url'=> 'https://vocabularyserver.com/archivistica/'),
'https://vocabularyserver.com/tbyd/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Biblioteconomía y Documentación ','url'=> 'https://vocabularyserver.com/tbyd/'),
'https://vocabularyserver.com/docutes/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Ciencias de la Documentación ','url'=> 'https://vocabularyserver.com/docutes/es/'),
'https://vocabularyserver.com/tesamat/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Ciencias Matemáticas ','url'=> 'https://vocabularyserver.com/tesamat/'),
'https://vocabularyserver.com/cine/ suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de cine ','url'=> 'https://vocabularyserver.com/cine/ '),
'https://vocabularyserver.com/cadiz/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de documentacion audiovisual ','url'=> 'https://vocabularyserver.com/cadiz/'),
'https://vocabularyserver.com/tes/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de educación superior ','url'=> 'https://vocabularyserver.com/tes/'),
'https://vocabularyserver.com/floricultura/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de FLORICULTURA ','url'=> 'https://vocabularyserver.com/floricultura/'),
'https://vocabularyserver.com/ficcion/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de géneros de ficción ','url'=> 'https://vocabularyserver.com/ficcion/es/'),
'https://vocabularyserver.com/hidrocarburos/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Hidrocarburos ','url'=> 'https://vocabularyserver.com/hidrocarburos/'),
'https://vocabularyserver.com/historiamujeres/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de historia de las mujeres ','url'=> 'https://vocabularyserver.com/historiamujeres/'),
'https://vocabularyserver.com/tina/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de información de actualidad ','url'=> 'https://vocabularyserver.com/tina/'),
'https://vocabularyserver.com/nal/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de la Biblioteca Nacional de Agricultura ','url'=> 'https://vocabularyserver.com/nal/es/'),
'https://vocabularyserver.com/unesco/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de la UNESCO ','url'=> 'https://vocabularyserver.com/unesco/es/'),
'https://vocabularyserver.com/traces/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de lengua y literatura ','url'=> 'https://vocabularyserver.com/traces/es/'),
'https://vocabularyserver.com/rarothes/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Libro Antiguo y Raro ','url'=> 'https://vocabularyserver.com/rarothes/'),
'https://vocabularyserver.com/bll/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de linguística ','url'=> 'https://vocabularyserver.com/bll/es/'),
'https://vocabularyserver.com/migraciones/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Migraciones Internacionales Contemporáneas ','url'=> 'https://vocabularyserver.com/migraciones/'),
'https://vocabularyserver.com/mujeres/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de mujeres ','url'=> 'https://vocabularyserver.com/mujeres/'),
'https://vocabularyserver.com/psicologia/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Psicología ','url'=> 'https://vocabularyserver.com/psicologia/'),
'https://vocabularyserver.com/psicothes/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Psicología Argentina ','url'=> 'https://vocabularyserver.com/psicothes/'),
'https://vocabularyserver.com/turismo/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de Turismo ','url'=> 'https://vocabularyserver.com/turismo/'),
'https://vocabularyserver.com/ttla/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro de turismo y ocio ','url'=> 'https://vocabularyserver.com/ttla/es/'),
'https://vocabularyserver.com/intal/tesauro/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro del INTAL ','url'=> 'https://vocabularyserver.com/intal/tesauro/'),
'https://vocabularyserver.com/smdh/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro del Sistema de Monitoreo en Derechos Humanos ','url'=> 'https://vocabularyserver.com/smdh/'),
'https://vocabularyserver.com/genero/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro especializado en filosofía, con enfoque de género ','url'=> 'https://vocabularyserver.com/genero/'),
'https://vocabularyserver.com/tee/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro Europeo de la Educación ','url'=> 'https://vocabularyserver.com/tee/es/'),
'https://vocabularyserver.com/toponimos/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro Geográfico ','url'=> 'https://vocabularyserver.com/toponimos/'),
'https://vocabularyserver.com/cortesupremamx/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro Jurídico de la Suprema Corte de Justicia de la Nación ','url'=> 'https://vocabularyserver.com/cortesupremamx/'),
'https://vocabularyserver.com/espaciop/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro para la colección Espacio P ','url'=> 'https://vocabularyserver.com/espaciop/'),
'https://vocabularyserver.com/redprodepaz/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro Redprodepaz ','url'=> 'https://vocabularyserver.com/redprodepaz/'),
'https://vocabularyserver.com/corteidh/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro sobre derechos humanos ','url'=> 'https://vocabularyserver.com/corteidh/'),
'https://vocabularyserver.com/unbis/es/suggest.php' => array('lang' => 'Spanish','name' => 'Tesauro UNBIS ','url'=> 'https://vocabularyserver.com/unbis/es/'),
'https://vocabularyserver.com/eurydice/es/suggest.php' => array('lang' => 'Spanish','name' => 'TESE - Tesauro Europeo de los Sistemas Educativos ','url'=> 'https://vocabularyserver.com/eurydice/es/'),
'https://vocabularyserver.com/thema/es/suggest.php' => array('lang' => 'Spanish','name' => 'Thema 1.3: clasificación temática para editoriales y librerías ','url'=> 'https://vocabularyserver.com/thema/es/'),
'https://vocabularyserver.com/ts/suggest.php' => array('lang' => 'Spanish','name' => 'Trabajo Social ','url'=> 'https://vocabularyserver.com/ts/'),
'https://vocabularyserver.com/vitruvio/suggest.php' => array('lang' => 'Spanish','name' => 'Vitruvio ','url'=> 'https://vocabularyserver.com/vitruvio/'),
'https://vocabularyserver.com/sedronar/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario Controlado SEDRONAR ','url'=> 'https://vocabularyserver.com/sedronar/'),
'https://vocabularyserver.com/filo/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario de la Biblioteca Central de la FFyL ','url'=> 'https://vocabularyserver.com/filo/'),
'https://vocabularyserver.com/carne/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario de la Carne Vacuna Argentina ','url'=> 'https://vocabularyserver.com/carne/'),
'https://vocabularyserver.com/vocabularioelectoral/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario Electoral Argentino ','url'=> 'https://vocabularyserver.com/vocabularioelectoral/'),
'https://vocabularyserver.com//tesaurojuridico/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario Latinoamericano de Derecho ','url'=> 'https://vocabularyserver.com//tesaurojuridico/'),
'https://vocabularyserver.com/consumidor/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario sobre Derechos de los consumidores ','url'=> 'https://vocabularyserver.com/consumidor/'),
'https://vocabularyserver.com/vocabulariorse/suggest.php' => array('lang' => 'Spanish','name' => 'Vocabulario sobre Responsabilidad Social ','url'=> 'https://vocabularyserver.com/vocabulariorse/'),
'https://vocabularyserver.com/eurovoc/sv/suggest.php' => array('lang' => 'Swedish','name' => 'Eurovoc, EU:s flerspråkiga tesaurus ','url'=> 'https://vocabularyserver.com/eurovoc/sv/'),
'https://vocabularyserver.com/lre/sv/ suggest.php' => array('lang' => 'Swedish','name' => 'LRE  thesaurus','url'=> 'https://vocabularyserver.com/lre/sv/ '),
    );

    /**
     * Find a suggest record by element ID.
     *
     * @param int|string $elementId
     * @return T3Suggest|null
     */
    public function findByElementId($elementId)
    {
        $select = $this->getSelect()->where('element_id = ?', $elementId);
        return $this->fetchObject($select);
    }

    /**
     * Get the suggest endpoints.
     *
     * @return array
     */
    public function getSuggestEndpoints()
    {
        return $this->_suggestEndpoints;
    }
}
